2024-10-30T02:41:38 'life'
2024-10-30T02:41:38 'life'
2024-10-30T02:41:38 '  File "quest.py", line 741, in <module>\n    poe_bot.refreshAll()\n'
2024-10-30T02:41:38 '  File "D:\\poe_bot\\1_host\\utils\\gamehelper.py", line 232, in refreshAll\n    self.game_data.update(refreshed_data=refreshed_data, refresh_visited=refresh_visited)\n'
2024-10-30T02:41:38 '  File "D:\\poe_bot\\1_host\\utils\\gamehelper.py", line 974, in update\n    self.life_object = refreshed_data["life"]\n'
2024-10-30T02:43:22 'life'
2024-10-30T02:43:22 'life'
2024-10-30T02:43:22 '  File "quest.py", line 741, in <module>\n    poe_bot.refreshAll()\n'
2024-10-30T02:43:22 '  File "D:\\poe_bot\\1_host\\utils\\gamehelper.py", line 232, in refreshAll\n    self.game_data.update(refreshed_data=refreshed_data, refresh_visited=refresh_visited)\n'
2024-10-30T02:43:22 '  File "D:\\poe_bot\\1_host\\utils\\gamehelper.py", line 974, in update\n    labels = self.poe_bot.backend.getVisibleLabelOnGroundEntities()\n'
2024-10-30T02:43:27 'NoneType' object has no attribute 'last_use_time'
2024-10-30T02:43:27 'NoneType' object has no attribute 'last_use_time'
2024-10-30T02:43:27 '  File "quest.py", line 4747, in <module>\n    current_quest_area.complete()\n'
2024-10-30T02:43:27 '  File "quest.py", line 1088, in complete\n    res = poe_bot.mover.goToPoint(\n'
2024-10-30T02:43:27 '  File "D:\\poe_bot\\1_host\\utils\\mover.py", line 463, in goToPoint\n    if bot_controls.mouse_pressed[\'left\'] is True and custom_continue_function(self) is True:\n'
2024-10-30T02:43:27 '  File "quest.py", line 460, in usualRoutine\n    if self.attacking_skill.last_use_time + attacking_skill_delay < time.time():\n'
2024-10-30T02:46:24 'NoneType' object has no attribute 'last_use_time'
2024-10-30T02:46:24 'NoneType' object has no attribute 'last_use_time'
2024-10-30T02:46:24 '  File "quest.py", line 4747, in <module>\n    current_quest_area.complete()\n'
2024-10-30T02:46:24 '  File "quest.py", line 1088, in complete\n    res = poe_bot.mover.goToPoint(\n'
2024-10-30T02:46:24 '  File "D:\\poe_bot\\1_host\\utils\\mover.py", line 463, in goToPoint\n    if bot_controls.mouse_pressed[\'left\'] is True and custom_continue_function(self) is True:\n'
2024-10-30T02:46:24 '  File "quest.py", line 460, in usualRoutine\n    if self.attacking_skill.last_use_time + attacking_skill_delay < time.time():\n'
2024-10-30T02:46:30 'NoneType' object has no attribute 'last_use_time'
2024-10-30T02:46:30 'NoneType' object has no attribute 'last_use_time'
2024-10-30T02:46:30 '  File "quest.py", line 4747, in <module>\n    current_quest_area.complete()\n'
2024-10-30T02:46:30 '  File "quest.py", line 1088, in complete\n    res = poe_bot.mover.goToPoint(\n'
2024-10-30T02:46:30 '  File "D:\\poe_bot\\1_host\\utils\\mover.py", line 463, in goToPoint\n    if bot_controls.mouse_pressed[\'left\'] is True and custom_continue_function(self) is True:\n'
2024-10-30T02:46:30 '  File "quest.py", line 460, in usualRoutine\n    if self.attacking_skill.last_use_time + attacking_skill_delay < time.time():\n'
2024-10-30T02:50:51 #resurrectAtCheckpoint call 1730227851.3457384
2024-10-30T02:52:55 #resurrectAtCheckpoint call 1730227975.0809293
2024-10-30T02:54:30 exceptions must derive from BaseException
2024-10-30T02:54:30 exceptions must derive from BaseException
2024-10-30T02:54:30 '  File "quest.py", line 4747, in <module>\n    current_quest_area.complete()\n'
2024-10-30T02:54:30 '  File "quest.py", line 1183, in complete\n    raise "completed"\n'
2024-10-30T02:57:13 #resurrectAtCheckpoint call 1730228233.089479
2024-10-30T02:58:22 #resurrectAtCheckpoint call 1730228302.5545466
2024-10-30T03:01:31 relogging through char select screen
2024-10-30T03:01:31 getting to char selection screen from game
2024-10-30T03:04:20 couldnt check the key
2024-10-30T03:04:20 couldnt check the key
2024-10-30T03:04:20 '  File "quest.py", line 732, in <module>\n    poe_bot = PoeBot(unique_id=UNIQUE_ID, remote_ip = REMOTE_IP, debug = notebook_dev)\n'
2024-10-30T03:04:20 '  File "D:\\poe_bot\\1_host\\utils\\gamehelper.py", line 101, in __init__\n    self.checkIfReady()\n'
2024-10-30T03:04:20 '  File "D:\\poe_bot\\1_host\\utils\\gamehelper.py", line 142, in checkIfReady\n    raise Exception(\'couldnt check the key\')\n'
2024-10-30T03:08:21 #resurrectAtCheckpoint call 1730228901.693661
2024-10-30T03:09:55 #resurrectAtCheckpoint call 1730228995.2374935
2024-10-30T03:11:40 exceptions must derive from BaseException
2024-10-30T03:11:40 exceptions must derive from BaseException
2024-10-30T03:11:40 '  File "quest.py", line 4747, in <module>\n    current_quest_area.complete()\n'
2024-10-30T03:11:40 '  File "quest.py", line 1183, in complete\n    raise "completed"\n'
2024-10-30T03:16:10 #resurrectAtCheckpoint call 1730229370.407763
2024-10-30T03:17:04 #resurrectAtCheckpoint call 1730229424.5564444
2024-10-30T03:18:18 relogging through char select screen
2024-10-30T03:18:18 getting to char selection screen from game
2024-10-30T03:26:56 exceptions must derive from BaseException
2024-10-30T03:26:56 exceptions must derive from BaseException
2024-10-30T03:26:56 '  File "quest.py", line 4747, in <module>\n    current_quest_area.complete()\n'
2024-10-30T03:26:56 '  File "quest.py", line 1183, in complete\n    raise "completed"\n'
2024-10-30T03:28:05 #resurrectAtCheckpoint call 1730230085.1300528
2024-10-30T03:33:24 #resurrectAtCheckpoint call 1730230404.4830632
2024-10-30T03:34:23 #resurrectAtCheckpoint call 1730230463.2245681
2024-10-30T03:35:24 #resurrectAtCheckpoint call 1730230524.2956138
2024-10-30T03:36:36 #resurrectAtCheckpoint call 1730230596.696744
2024-10-30T03:41:40 #resurrectAtCheckpoint call 1730230900.2070282
2024-10-30T03:43:00 #resurrectAtCheckpoint call 1730230980.2837155
2024-10-30T03:44:16 #resurrectAtCheckpoint call 1730231056.4286315
2024-10-30T03:45:30 #resurrectAtCheckpoint call 1730231130.6468818
2024-10-30T03:46:25 #resurrectAtCheckpoint call 1730231185.1791005
2024-10-30T03:47:37 #resurrectAtCheckpoint call 1730231257.7628574
2024-10-30T03:53:14 #resurrectAtCheckpoint call 1730231594.6858249
2024-10-30T03:56:47 relogging through char select screen
2024-10-30T03:56:47 getting to char selection screen from game
2024-10-30T22:36:22 #resurrectAtCheckpoint call 1730298982.845938
2024-10-30T22:36:40 #resurrectAtCheckpoint call 1730299000.29398
2024-10-30T22:37:16 #resurrectAtCheckpoint call 1730299036.0535371
2024-10-30T22:37:33 #resurrectAtCheckpoint call 1730299053.0235932
2024-10-30T22:37:49 #resurrectAtCheckpoint call 1730299069.057447
2024-10-30T22:38:09 #resurrectAtCheckpoint call 1730299089.6954172
2024-10-30T22:38:28 #resurrectAtCheckpoint call 1730299108.9871185
2024-10-30T22:38:45 #resurrectAtCheckpoint call 1730299125.519787
2024-10-30T22:39:01 #resurrectAtCheckpoint call 1730299141.1790683
2024-10-30T22:39:21 #resurrectAtCheckpoint call 1730299161.6955178
2024-10-30T22:48:11 1_2_town current area isn't supported
2024-10-30T22:48:11 1_2_town current area isn't supported
2024-10-30T22:48:11 '  File "quest.py", line 4811, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-10-30T22:48:11 '  File "quest.py", line 4801, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-10-30T22:48:13 1_2_town current area isn't supported
2024-10-30T22:48:13 1_2_town current area isn't supported
2024-10-30T22:48:13 '  File "quest.py", line 4811, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-10-30T22:48:13 '  File "quest.py", line 4801, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-10-30T22:48:14 1_2_town current area isn't supported
2024-10-30T22:48:14 1_2_town current area isn't supported
2024-10-30T22:48:14 '  File "quest.py", line 4811, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-10-30T22:48:14 '  File "quest.py", line 4801, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-10-30T22:48:16 1_2_town current area isn't supported
2024-10-30T22:48:16 1_2_town current area isn't supported
2024-10-30T22:48:16 '  File "quest.py", line 4811, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-10-30T22:48:16 '  File "quest.py", line 4801, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-10-30T22:48:18 1_2_town current area isn't supported
2024-10-30T22:48:18 1_2_town current area isn't supported
2024-10-30T22:48:18 '  File "quest.py", line 4811, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-10-30T22:48:18 '  File "quest.py", line 4801, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-10-30T22:48:21 1_2_town current area isn't supported
2024-10-30T22:48:21 1_2_town current area isn't supported
2024-10-30T22:48:21 '  File "quest.py", line 4811, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-10-30T22:48:21 '  File "quest.py", line 4801, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-10-30T22:48:23 1_2_town current area isn't supported
2024-10-30T22:48:23 1_2_town current area isn't supported
2024-10-30T22:48:23 '  File "quest.py", line 4811, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-10-30T22:48:23 '  File "quest.py", line 4801, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-10-30T22:48:26 1_2_town current area isn't supported
2024-10-30T22:48:26 1_2_town current area isn't supported
2024-10-30T22:48:26 '  File "quest.py", line 4811, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-10-30T22:48:26 '  File "quest.py", line 4801, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-10-30T22:48:28 1_2_town current area isn't supported
2024-10-30T22:48:28 1_2_town current area isn't supported
2024-10-30T22:48:28 '  File "quest.py", line 4811, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-10-30T22:48:28 '  File "quest.py", line 4801, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-10-30T22:48:31 1_2_town current area isn't supported
2024-10-30T22:48:31 1_2_town current area isn't supported
2024-10-30T22:48:31 '  File "quest.py", line 4811, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-10-30T22:48:31 '  File "quest.py", line 4801, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-10-30T22:48:33 1_2_town current area isn't supported
2024-10-30T22:48:33 1_2_town current area isn't supported
2024-10-30T22:48:33 '  File "quest.py", line 4811, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-10-30T22:48:33 '  File "quest.py", line 4801, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-10-30T22:48:36 1_2_town current area isn't supported
2024-10-30T22:48:36 1_2_town current area isn't supported
2024-10-30T22:48:36 '  File "quest.py", line 4811, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-10-30T22:48:36 '  File "quest.py", line 4801, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-10-30T22:48:38 1_2_town current area isn't supported
2024-10-30T22:48:38 1_2_town current area isn't supported
2024-10-30T22:48:38 '  File "quest.py", line 4811, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-10-30T22:48:38 '  File "quest.py", line 4801, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-10-30T22:48:42 1_2_town current area isn't supported
2024-10-30T22:48:42 1_2_town current area isn't supported
2024-10-30T22:48:42 '  File "quest.py", line 4811, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-10-30T22:48:42 '  File "quest.py", line 4801, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-10-30T22:48:44 1_2_town current area isn't supported
2024-10-30T22:48:44 1_2_town current area isn't supported
2024-10-30T22:48:44 '  File "quest.py", line 4811, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-10-30T22:48:44 '  File "quest.py", line 4801, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-10-30T22:48:47 1_2_town current area isn't supported
2024-10-30T22:48:47 1_2_town current area isn't supported
2024-10-30T22:48:47 '  File "quest.py", line 4811, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-10-30T22:48:47 '  File "quest.py", line 4801, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-10-30T22:48:50 1_2_town current area isn't supported
2024-10-30T22:48:50 1_2_town current area isn't supported
2024-10-30T22:48:50 '  File "quest.py", line 4811, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-10-30T22:48:50 '  File "quest.py", line 4801, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-10-30T22:48:52 1_2_town current area isn't supported
2024-10-30T22:48:52 1_2_town current area isn't supported
2024-10-30T22:48:52 '  File "quest.py", line 4811, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-10-30T22:48:52 '  File "quest.py", line 4801, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-10-30T22:48:54 1_2_town current area isn't supported
2024-10-30T22:48:54 1_2_town current area isn't supported
2024-10-30T22:48:54 '  File "quest.py", line 4811, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-10-30T22:48:54 '  File "quest.py", line 4801, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-10-30T22:48:56 1_2_town current area isn't supported
2024-10-30T22:48:56 1_2_town current area isn't supported
2024-10-30T22:48:56 '  File "quest.py", line 4811, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-10-30T22:48:56 '  File "quest.py", line 4801, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-10-30T22:49:00 1_2_town current area isn't supported
2024-10-30T22:49:00 1_2_town current area isn't supported
2024-10-30T22:49:00 '  File "quest.py", line 4811, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-10-30T22:49:00 '  File "quest.py", line 4801, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-10-30T22:49:02 1_2_town current area isn't supported
2024-10-30T22:49:02 1_2_town current area isn't supported
2024-10-30T22:49:02 '  File "quest.py", line 4811, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-10-30T22:49:02 '  File "quest.py", line 4801, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-10-30T22:49:05 1_2_town current area isn't supported
2024-10-30T22:49:05 1_2_town current area isn't supported
2024-10-30T22:49:05 '  File "quest.py", line 4811, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-10-30T22:49:05 '  File "quest.py", line 4801, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-10-30T22:49:08 1_2_town current area isn't supported
2024-10-30T22:49:08 1_2_town current area isn't supported
2024-10-30T22:49:08 '  File "quest.py", line 4811, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-10-30T22:49:08 '  File "quest.py", line 4801, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-10-30T22:49:10 1_2_town current area isn't supported
2024-10-30T22:49:10 1_2_town current area isn't supported
2024-10-30T22:49:10 '  File "quest.py", line 4811, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-10-30T22:49:10 '  File "quest.py", line 4801, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-10-30T22:49:14 1_2_town current area isn't supported
2024-10-30T22:49:14 1_2_town current area isn't supported
2024-10-30T22:49:14 '  File "quest.py", line 4811, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-10-30T22:49:14 '  File "quest.py", line 4801, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-10-30T22:49:16 1_2_town current area isn't supported
2024-10-30T22:49:16 1_2_town current area isn't supported
2024-10-30T22:49:16 '  File "quest.py", line 4811, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-10-30T22:49:16 '  File "quest.py", line 4801, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-10-30T22:49:19 1_2_town current area isn't supported
2024-10-30T22:49:19 1_2_town current area isn't supported
2024-10-30T22:49:19 '  File "quest.py", line 4811, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-10-30T22:49:19 '  File "quest.py", line 4801, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-10-30T22:49:21 1_2_town current area isn't supported
2024-10-30T22:49:21 1_2_town current area isn't supported
2024-10-30T22:49:21 '  File "quest.py", line 4811, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-10-30T22:49:21 '  File "quest.py", line 4801, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-10-30T22:55:47 #resurrectAtCheckpoint call 1730300147.8852396
