2024-10-11T09:44:56 #resurrectAtCheckpoint call 1728611096.0677483
2024-10-11T09:48:13 exceptions must derive from BaseException
2024-10-11T09:48:13 exceptions must derive from BaseException
2024-10-11T09:48:13 '  File "quest.py", line 4667, in <module>\n    current_quest_area.complete()\n'
2024-10-11T09:48:13 '  File "quest.py", line 1161, in complete\n    raise "completed"\n'
2024-10-11T09:53:55 #resurrectAtCheckpoint call 1728611635.0960824
2024-10-11T09:57:32 relogging through char select screen
2024-10-11T09:57:32 getting to char selection screen from game
2024-10-11T10:32:08 '<' not supported between instances of 'list' and 'dict'
2024-10-11T10:32:08 '<' not supported between instances of 'list' and 'dict'
2024-10-11T10:32:08 '  File "quest.py", line 4679, in <module>\n    current_quest_area.complete()\n'
2024-10-11T10:32:08 '  File "quest.py", line 1078, in complete\n    res = poe_bot.mover.goToPoint(\n'
2024-10-11T10:32:08 '  File "C:\\poe_bot\\1_host\\utils\\mover.py", line 463, in goToPoint\n    if bot_controls.mouse_pressed[\'left\'] is True and custom_continue_function(self) is True:\n'
2024-10-11T10:32:08 '  File "quest.py", line 480, in usualRoutine\n    if alive_zombies_nearby < self.max_amount_of_zombies:\n'
2024-10-11T10:33:57 '<' not supported between instances of 'list' and 'int'
2024-10-11T10:33:57 '<' not supported between instances of 'list' and 'int'
2024-10-11T10:33:57 '  File "quest.py", line 4681, in <module>\n    current_quest_area.complete()\n'
2024-10-11T10:33:57 '  File "quest.py", line 1080, in complete\n    res = poe_bot.mover.goToPoint(\n'
2024-10-11T10:33:57 '  File "C:\\poe_bot\\1_host\\utils\\mover.py", line 463, in goToPoint\n    if bot_controls.mouse_pressed[\'left\'] is True and custom_continue_function(self) is True:\n'
2024-10-11T10:33:57 '  File "quest.py", line 482, in usualRoutine\n    if alive_zombies_nearby < self.max_amount_of_zombies:\n'
2024-10-11T10:34:00 '<' not supported between instances of 'list' and 'int'
2024-10-11T10:34:00 '<' not supported between instances of 'list' and 'int'
2024-10-11T10:34:00 '  File "quest.py", line 4681, in <module>\n    current_quest_area.complete()\n'
2024-10-11T10:34:00 '  File "quest.py", line 1080, in complete\n    res = poe_bot.mover.goToPoint(\n'
2024-10-11T10:34:00 '  File "C:\\poe_bot\\1_host\\utils\\mover.py", line 463, in goToPoint\n    if bot_controls.mouse_pressed[\'left\'] is True and custom_continue_function(self) is True:\n'
2024-10-11T10:34:00 '  File "quest.py", line 482, in usualRoutine\n    if alive_zombies_nearby < self.max_amount_of_zombies:\n'
2024-10-11T10:45:00 couldnt check the key
2024-10-11T10:45:00 couldnt check the key
2024-10-11T10:45:00 '  File "quest.py", line 724, in <module>\n    poe_bot = PoeBot(unique_id=UNIQUE_ID, remote_ip = REMOTE_IP, debug = notebook_dev)\n'
2024-10-11T10:45:00 '  File "C:\\poe_bot\\1_host\\utils\\gamehelper.py", line 101, in __init__\n    self.checkIfReady()\n'
2024-10-11T10:45:00 '  File "C:\\poe_bot\\1_host\\utils\\gamehelper.py", line 142, in checkIfReady\n    raise Exception(\'couldnt check the key\')\n'
2024-10-11T12:13:27 relogging through char select screen
2024-10-11T12:13:27 getting to char selection screen from game
2024-10-11T15:47:01 #resurrectAtCheckpoint call 1728632821.7187293
2024-10-11T15:47:19 #resurrectAtCheckpoint call 1728632839.4093914
2024-10-11T15:47:40 #resurrectAtCheckpoint call 1728632860.511665
2024-10-11T15:47:57 #resurrectAtCheckpoint call 1728632877.7411728
2024-10-11T15:48:12 #resurrectAtCheckpoint call 1728632892.1635652
2024-10-11T15:48:27 #resurrectAtCheckpoint call 1728632907.1185622
2024-10-11T15:48:55 #resurrectAtCheckpoint call 1728632935.705354
2024-10-11T15:49:11 #resurrectAtCheckpoint call 1728632951.3488967
2024-10-11T15:49:27 #resurrectAtCheckpoint call 1728632967.3044767
2024-10-11T15:49:40 #resurrectAtCheckpoint call 1728632980.2952735
2024-10-11T15:50:01 #resurrectAtCheckpoint call 1728633001.229232
2024-10-11T15:50:34 #resurrectAtCheckpoint call 1728633034.9348223
2024-10-11T15:50:46 #resurrectAtCheckpoint call 1728633046.8184474
2024-10-11T15:50:59 #resurrectAtCheckpoint call 1728633059.6329472
2024-10-11T15:51:16 #resurrectAtCheckpoint call 1728633076.9459865
2024-10-11T15:55:09 list index out of range
2024-10-11T15:55:09 list index out of range
2024-10-11T15:55:09 '  File "quest.py", line 734, in <module>\n    poe_bot.game_data.terrain.getCurrentlyPassableArea()\n'
2024-10-11T15:55:09 '  File "C:\\poe_bot\\1_host\\utils\\gamehelper.py", line 503, in getCurrentlyPassableArea\n    nearest_passable_player_point = list(list(zip(nearest_passable_player_points[0], nearest_passable_player_points[1]))[0])\n'
2024-10-11T16:20:18 #resurrectAtCheckpoint call 1728634818.8146315
2024-10-11T16:20:50 #resurrectAtCheckpoint call 1728634850.036631
2024-10-11T16:31:13 #resurrectAtCheckpoint call 1728635473.5413375
2024-10-11T16:44:39 list index out of range
2024-10-11T16:44:39 list index out of range
2024-10-11T16:44:39 '  File "quest.py", line 742, in <module>\n    poe_bot.game_data.terrain.getCurrentlyPassableArea()\n'
2024-10-11T16:44:39 '  File "C:\\poe_bot\\1_host\\utils\\gamehelper.py", line 503, in getCurrentlyPassableArea\n    nearest_passable_player_point = list(list(zip(nearest_passable_player_points[0], nearest_passable_player_points[1]))[0])\n'
2024-10-11T16:58:40 #resurrectAtCheckpoint call 1728637120.8976831
2024-10-11T17:05:50 #resurrectAtCheckpoint call 1728637550.9451087
2024-10-11T17:06:44 relogging through char select screen
2024-10-11T17:06:44 getting to char selection screen from game
2024-10-11T17:07:17 1_2_town current area isn't supported
2024-10-11T17:07:17 1_2_town current area isn't supported
2024-10-11T17:07:17 '  File "quest.py", line 4694, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-10-11T17:07:17 '  File "quest.py", line 4684, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-10-11T17:07:20 1_2_town current area isn't supported
2024-10-11T17:07:20 1_2_town current area isn't supported
2024-10-11T17:07:20 '  File "quest.py", line 4694, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-10-11T17:07:20 '  File "quest.py", line 4684, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-10-11T17:07:23 1_2_town current area isn't supported
2024-10-11T17:07:23 1_2_town current area isn't supported
2024-10-11T17:07:23 '  File "quest.py", line 4694, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-10-11T17:07:23 '  File "quest.py", line 4684, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-10-11T17:07:26 1_2_town current area isn't supported
2024-10-11T17:07:26 1_2_town current area isn't supported
2024-10-11T17:07:26 '  File "quest.py", line 4694, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-10-11T17:07:26 '  File "quest.py", line 4684, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-10-11T17:07:29 1_2_town current area isn't supported
2024-10-11T17:07:29 1_2_town current area isn't supported
2024-10-11T17:07:29 '  File "quest.py", line 4694, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-10-11T17:07:29 '  File "quest.py", line 4684, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-10-11T17:07:31 1_2_town current area isn't supported
2024-10-11T17:07:31 1_2_town current area isn't supported
2024-10-11T17:07:31 '  File "quest.py", line 4694, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-10-11T17:07:31 '  File "quest.py", line 4684, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-10-11T17:07:34 1_2_town current area isn't supported
2024-10-11T17:07:34 1_2_town current area isn't supported
2024-10-11T17:07:34 '  File "quest.py", line 4694, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-10-11T17:07:34 '  File "quest.py", line 4684, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-10-11T17:07:38 1_2_town current area isn't supported
2024-10-11T17:07:38 1_2_town current area isn't supported
2024-10-11T17:07:38 '  File "quest.py", line 4694, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-10-11T17:07:38 '  File "quest.py", line 4684, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-10-11T17:07:40 1_2_town current area isn't supported
2024-10-11T17:07:40 1_2_town current area isn't supported
2024-10-11T17:07:40 '  File "quest.py", line 4694, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-10-11T17:07:40 '  File "quest.py", line 4684, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-10-11T17:07:43 1_2_town current area isn't supported
2024-10-11T17:07:43 1_2_town current area isn't supported
2024-10-11T17:07:43 '  File "quest.py", line 4694, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-10-11T17:07:43 '  File "quest.py", line 4684, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-10-11T17:07:46 1_2_town current area isn't supported
2024-10-11T17:07:46 1_2_town current area isn't supported
2024-10-11T17:07:46 '  File "quest.py", line 4694, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-10-11T17:07:46 '  File "quest.py", line 4684, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-10-11T17:07:48 1_2_town current area isn't supported
2024-10-11T17:07:48 1_2_town current area isn't supported
2024-10-11T17:07:48 '  File "quest.py", line 4694, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-10-11T17:07:48 '  File "quest.py", line 4684, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-10-11T17:07:51 1_2_town current area isn't supported
2024-10-11T17:07:51 1_2_town current area isn't supported
2024-10-11T17:07:51 '  File "quest.py", line 4694, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-10-11T17:07:51 '  File "quest.py", line 4684, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-10-11T17:07:53 1_2_town current area isn't supported
2024-10-11T17:07:53 1_2_town current area isn't supported
2024-10-11T17:07:53 '  File "quest.py", line 4694, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-10-11T17:07:53 '  File "quest.py", line 4684, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-10-11T17:07:56 1_2_town current area isn't supported
2024-10-11T17:07:56 1_2_town current area isn't supported
2024-10-11T17:07:56 '  File "quest.py", line 4694, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-10-11T17:07:56 '  File "quest.py", line 4684, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-10-11T17:07:59 1_2_town current area isn't supported
2024-10-11T17:07:59 1_2_town current area isn't supported
2024-10-11T17:07:59 '  File "quest.py", line 4694, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-10-11T17:07:59 '  File "quest.py", line 4684, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-10-11T17:08:01 1_2_town current area isn't supported
2024-10-11T17:08:01 1_2_town current area isn't supported
2024-10-11T17:08:01 '  File "quest.py", line 4694, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-10-11T17:08:01 '  File "quest.py", line 4684, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-10-11T17:08:04 1_2_town current area isn't supported
2024-10-11T17:08:04 1_2_town current area isn't supported
2024-10-11T17:08:04 '  File "quest.py", line 4694, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-10-11T17:08:04 '  File "quest.py", line 4684, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-10-11T17:08:07 1_2_town current area isn't supported
2024-10-11T17:08:07 1_2_town current area isn't supported
2024-10-11T17:08:07 '  File "quest.py", line 4694, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-10-11T17:08:07 '  File "quest.py", line 4684, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-10-11T17:08:09 1_2_town current area isn't supported
2024-10-11T17:08:09 1_2_town current area isn't supported
2024-10-11T17:08:09 '  File "quest.py", line 4694, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-10-11T17:08:09 '  File "quest.py", line 4684, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-10-11T17:08:13 1_2_town current area isn't supported
2024-10-11T17:08:13 1_2_town current area isn't supported
2024-10-11T17:08:13 '  File "quest.py", line 4694, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-10-11T17:08:13 '  File "quest.py", line 4684, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-10-11T17:08:15 1_2_town current area isn't supported
2024-10-11T17:08:15 1_2_town current area isn't supported
2024-10-11T17:08:15 '  File "quest.py", line 4694, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-10-11T17:08:15 '  File "quest.py", line 4684, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-10-11T17:08:17 1_2_town current area isn't supported
2024-10-11T17:08:17 1_2_town current area isn't supported
2024-10-11T17:08:17 '  File "quest.py", line 4694, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-10-11T17:08:17 '  File "quest.py", line 4684, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-10-11T17:08:21 1_2_town current area isn't supported
2024-10-11T17:08:21 1_2_town current area isn't supported
2024-10-11T17:08:21 '  File "quest.py", line 4694, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-10-11T17:08:21 '  File "quest.py", line 4684, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-10-11T17:08:23 1_2_town current area isn't supported
2024-10-11T17:08:23 1_2_town current area isn't supported
2024-10-11T17:08:23 '  File "quest.py", line 4694, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-10-11T17:08:23 '  File "quest.py", line 4684, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-10-11T17:08:26 1_2_town current area isn't supported
2024-10-11T17:08:26 1_2_town current area isn't supported
2024-10-11T17:08:26 '  File "quest.py", line 4694, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-10-11T17:08:26 '  File "quest.py", line 4684, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-10-11T17:08:28 1_2_town current area isn't supported
2024-10-11T17:08:28 1_2_town current area isn't supported
2024-10-11T17:08:28 '  File "quest.py", line 4694, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-10-11T17:08:28 '  File "quest.py", line 4684, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-10-11T17:08:31 1_2_town current area isn't supported
2024-10-11T17:08:31 1_2_town current area isn't supported
2024-10-11T17:08:31 '  File "quest.py", line 4694, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-10-11T17:08:31 '  File "quest.py", line 4684, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-10-11T17:08:33 1_2_town current area isn't supported
2024-10-11T17:08:33 1_2_town current area isn't supported
2024-10-11T17:08:33 '  File "quest.py", line 4694, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-10-11T17:08:33 '  File "quest.py", line 4684, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-10-11T17:08:36 1_2_town current area isn't supported
2024-10-11T17:08:36 1_2_town current area isn't supported
2024-10-11T17:08:36 '  File "quest.py", line 4694, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-10-11T17:08:36 '  File "quest.py", line 4684, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-10-11T17:08:38 1_2_town current area isn't supported
2024-10-11T17:08:38 1_2_town current area isn't supported
2024-10-11T17:08:38 '  File "quest.py", line 4694, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-10-11T17:08:38 '  File "quest.py", line 4684, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-10-11T17:08:41 1_2_town current area isn't supported
2024-10-11T17:08:41 1_2_town current area isn't supported
2024-10-11T17:08:41 '  File "quest.py", line 4694, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-10-11T17:08:41 '  File "quest.py", line 4684, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-10-11T17:08:44 1_2_town current area isn't supported
2024-10-11T17:08:44 1_2_town current area isn't supported
2024-10-11T17:08:44 '  File "quest.py", line 4694, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-10-11T17:08:44 '  File "quest.py", line 4684, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-10-11T17:08:47 1_2_town current area isn't supported
2024-10-11T17:08:47 1_2_town current area isn't supported
2024-10-11T17:08:47 '  File "quest.py", line 4694, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-10-11T17:08:47 '  File "quest.py", line 4684, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-10-11T17:08:50 1_2_town current area isn't supported
2024-10-11T17:08:50 1_2_town current area isn't supported
2024-10-11T17:08:50 '  File "quest.py", line 4694, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-10-11T17:08:50 '  File "quest.py", line 4684, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-10-11T17:08:53 1_2_town current area isn't supported
2024-10-11T17:08:53 1_2_town current area isn't supported
2024-10-11T17:08:53 '  File "quest.py", line 4694, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-10-11T17:08:53 '  File "quest.py", line 4684, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-10-11T17:08:55 1_2_town current area isn't supported
2024-10-11T17:08:55 1_2_town current area isn't supported
2024-10-11T17:08:55 '  File "quest.py", line 4694, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-10-11T17:08:55 '  File "quest.py", line 4684, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-10-11T17:08:58 1_2_town current area isn't supported
2024-10-11T17:08:58 1_2_town current area isn't supported
2024-10-11T17:08:58 '  File "quest.py", line 4694, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-10-11T17:08:58 '  File "quest.py", line 4684, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-10-11T17:09:01 1_2_town current area isn't supported
2024-10-11T17:09:01 1_2_town current area isn't supported
2024-10-11T17:09:01 '  File "quest.py", line 4694, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-10-11T17:09:01 '  File "quest.py", line 4684, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-10-11T17:09:03 1_2_town current area isn't supported
2024-10-11T17:09:03 1_2_town current area isn't supported
2024-10-11T17:09:03 '  File "quest.py", line 4694, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-10-11T17:09:03 '  File "quest.py", line 4684, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-10-11T17:09:06 1_2_town current area isn't supported
2024-10-11T17:09:06 1_2_town current area isn't supported
2024-10-11T17:09:06 '  File "quest.py", line 4694, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-10-11T17:09:06 '  File "quest.py", line 4684, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-10-11T17:09:09 1_2_town current area isn't supported
2024-10-11T17:09:09 1_2_town current area isn't supported
2024-10-11T17:09:09 '  File "quest.py", line 4694, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-10-11T17:09:09 '  File "quest.py", line 4684, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-10-11T17:09:11 1_2_town current area isn't supported
2024-10-11T17:09:11 1_2_town current area isn't supported
2024-10-11T17:09:11 '  File "quest.py", line 4694, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-10-11T17:09:11 '  File "quest.py", line 4684, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-10-11T17:09:14 1_2_town current area isn't supported
2024-10-11T17:09:14 1_2_town current area isn't supported
2024-10-11T17:09:14 '  File "quest.py", line 4694, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-10-11T17:09:14 '  File "quest.py", line 4684, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-10-11T17:09:17 1_2_town current area isn't supported
2024-10-11T17:09:17 1_2_town current area isn't supported
2024-10-11T17:09:17 '  File "quest.py", line 4694, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-10-11T17:09:17 '  File "quest.py", line 4684, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-10-11T17:09:20 1_2_town current area isn't supported
2024-10-11T17:09:20 1_2_town current area isn't supported
2024-10-11T17:09:20 '  File "quest.py", line 4694, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-10-11T17:09:20 '  File "quest.py", line 4684, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-10-11T17:09:22 1_2_town current area isn't supported
2024-10-11T17:09:22 1_2_town current area isn't supported
2024-10-11T17:09:22 '  File "quest.py", line 4694, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-10-11T17:09:22 '  File "quest.py", line 4684, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-10-11T17:09:25 1_2_town current area isn't supported
2024-10-11T17:09:25 1_2_town current area isn't supported
2024-10-11T17:09:25 '  File "quest.py", line 4694, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-10-11T17:09:25 '  File "quest.py", line 4684, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-10-11T17:09:27 1_2_town current area isn't supported
2024-10-11T17:09:27 1_2_town current area isn't supported
2024-10-11T17:09:27 '  File "quest.py", line 4694, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-10-11T17:09:27 '  File "quest.py", line 4684, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-10-11T17:09:30 1_2_town current area isn't supported
2024-10-11T17:09:30 1_2_town current area isn't supported
2024-10-11T17:09:30 '  File "quest.py", line 4694, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-10-11T17:09:30 '  File "quest.py", line 4684, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-10-11T17:09:33 1_2_town current area isn't supported
2024-10-11T17:09:33 1_2_town current area isn't supported
2024-10-11T17:09:33 '  File "quest.py", line 4694, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-10-11T17:09:33 '  File "quest.py", line 4684, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-10-11T17:09:35 1_2_town current area isn't supported
2024-10-11T17:09:35 1_2_town current area isn't supported
2024-10-11T17:09:35 '  File "quest.py", line 4694, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-10-11T17:09:35 '  File "quest.py", line 4684, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-10-11T17:09:38 1_2_town current area isn't supported
2024-10-11T17:09:38 1_2_town current area isn't supported
2024-10-11T17:09:38 '  File "quest.py", line 4694, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-10-11T17:09:38 '  File "quest.py", line 4684, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-10-11T17:09:41 1_2_town current area isn't supported
2024-10-11T17:09:41 1_2_town current area isn't supported
2024-10-11T17:09:41 '  File "quest.py", line 4694, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-10-11T17:09:41 '  File "quest.py", line 4684, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-10-11T17:09:43 1_2_town current area isn't supported
2024-10-11T17:09:43 1_2_town current area isn't supported
2024-10-11T17:09:43 '  File "quest.py", line 4694, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-10-11T17:09:43 '  File "quest.py", line 4684, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-10-11T17:09:46 1_2_town current area isn't supported
2024-10-11T17:09:46 1_2_town current area isn't supported
2024-10-11T17:09:46 '  File "quest.py", line 4694, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-10-11T17:09:46 '  File "quest.py", line 4684, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-10-11T17:09:49 1_2_town current area isn't supported
2024-10-11T17:09:49 1_2_town current area isn't supported
2024-10-11T17:09:49 '  File "quest.py", line 4694, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-10-11T17:09:49 '  File "quest.py", line 4684, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-10-11T17:09:53 1_2_town current area isn't supported
2024-10-11T17:09:53 1_2_town current area isn't supported
2024-10-11T17:09:53 '  File "quest.py", line 4694, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-10-11T17:09:53 '  File "quest.py", line 4684, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-10-11T17:09:56 1_2_town current area isn't supported
2024-10-11T17:09:56 1_2_town current area isn't supported
2024-10-11T17:09:56 '  File "quest.py", line 4694, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-10-11T17:09:56 '  File "quest.py", line 4684, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-10-11T17:09:59 1_2_town current area isn't supported
2024-10-11T17:09:59 1_2_town current area isn't supported
2024-10-11T17:09:59 '  File "quest.py", line 4694, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-10-11T17:09:59 '  File "quest.py", line 4684, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-10-11T17:10:02 1_2_town current area isn't supported
2024-10-11T17:10:02 1_2_town current area isn't supported
2024-10-11T17:10:02 '  File "quest.py", line 4694, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-10-11T17:10:02 '  File "quest.py", line 4684, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-10-11T17:10:05 1_2_town current area isn't supported
2024-10-11T17:10:05 1_2_town current area isn't supported
2024-10-11T17:10:05 '  File "quest.py", line 4694, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-10-11T17:10:05 '  File "quest.py", line 4684, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-10-11T17:10:08 1_2_town current area isn't supported
2024-10-11T17:10:08 1_2_town current area isn't supported
2024-10-11T17:10:08 '  File "quest.py", line 4694, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-10-11T17:10:08 '  File "quest.py", line 4684, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-10-11T17:10:10 1_2_town current area isn't supported
2024-10-11T17:10:10 1_2_town current area isn't supported
2024-10-11T17:10:10 '  File "quest.py", line 4694, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-10-11T17:10:10 '  File "quest.py", line 4684, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-10-11T17:19:23 1_3_town current area isn't supported
2024-10-11T17:19:23 1_3_town current area isn't supported
2024-10-11T17:19:23 '  File "quest.py", line 4694, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-10-11T17:19:23 '  File "quest.py", line 4684, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-10-11T17:19:27 1_3_town current area isn't supported
2024-10-11T17:19:27 1_3_town current area isn't supported
2024-10-11T17:19:27 '  File "quest.py", line 4694, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-10-11T17:19:27 '  File "quest.py", line 4684, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-10-11T17:19:30 1_3_town current area isn't supported
2024-10-11T17:19:30 1_3_town current area isn't supported
2024-10-11T17:19:30 '  File "quest.py", line 4694, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-10-11T17:19:30 '  File "quest.py", line 4684, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-10-11T17:19:33 1_3_town current area isn't supported
2024-10-11T17:19:33 1_3_town current area isn't supported
2024-10-11T17:19:33 '  File "quest.py", line 4694, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-10-11T17:19:33 '  File "quest.py", line 4684, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-10-11T17:19:52 1_3_town current area isn't supported
2024-10-11T17:19:52 1_3_town current area isn't supported
2024-10-11T17:19:52 '  File "quest.py", line 4694, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-10-11T17:19:52 '  File "quest.py", line 4684, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-10-11T17:26:10 #resurrectAtCheckpoint call 1728638770.4009562
2024-10-11T17:32:49 exceptions must derive from BaseException
2024-10-11T17:32:49 exceptions must derive from BaseException
2024-10-11T17:32:49 '  File "quest.py", line 4735, in <module>\n    current_quest_area.complete()\n'
2024-10-11T17:32:49 '  File "quest.py", line 1183, in complete\n    raise "completed"\n'
2024-10-11T17:38:11 exceptions must derive from BaseException
2024-10-11T17:38:11 exceptions must derive from BaseException
2024-10-11T17:38:11 '  File "quest.py", line 4735, in <module>\n    current_quest_area.complete()\n'
2024-10-11T17:38:11 '  File "quest.py", line 1183, in complete\n    raise "completed"\n'
2024-10-11T17:38:16 #resurrectAtCheckpoint call 1728639496.8448412
2024-10-11T17:45:52 exceptions must derive from BaseException
2024-10-11T17:45:52 exceptions must derive from BaseException
2024-10-11T17:45:52 '  File "quest.py", line 4735, in <module>\n    current_quest_area.complete()\n'
2024-10-11T17:45:52 '  File "quest.py", line 1183, in complete\n    raise "completed"\n'
2024-10-11T17:50:32 talk to dialla, goto other loc
2024-10-11T17:52:18 talk to dialla, goto other loc , sleep 3600*24
2024-10-11T17:52:18 talk to dialla, goto other loc , sleep 3600*24
2024-10-11T17:52:18 '  File "quest.py", line 4735, in <module>\n    current_quest_area.complete()\n'
2024-10-11T17:52:18 '  File "quest.py", line 1088, in complete\n    res = poe_bot.mover.goToPoint(\n'
2024-10-11T17:52:18 '  File "C:\\poe_bot\\1_host\\utils\\mover.py", line 459, in goToPoint\n    custom_break_function_result = custom_break_function(self)\n'
2024-10-11T17:52:18 '  File "quest.py", line 1024, in exploreRoutine\n    extra_quest_result = self.extraQuestInLoc()\n'
2024-10-11T17:52:18 '  File "quest.py", line 2969, in extraQuestInLoc\n    poe_bot.raiseLongSleepException(\'talk to dialla, goto other loc\')\n'
2024-10-11T17:52:18 '  File "C:\\poe_bot\\1_host\\utils\\gamehelper.py", line 351, in raiseLongSleepException\n    raiseLongSleepException(text)\n'
2024-10-11T17:52:18 '  File "C:\\poe_bot\\1_host\\utils\\utils.py", line 108, in raiseLongSleepException\n    raise Exception(f\'{text} , sleep 3600*24\')\n'
2024-10-11T17:58:39 supposed to have the key
2024-10-11T18:00:29 supposed to have the key , sleep 3600*24
2024-10-11T18:00:29 supposed to have the key , sleep 3600*24
2024-10-11T18:00:29 '  File "quest.py", line 4735, in <module>\n    current_quest_area.complete()\n'
2024-10-11T18:00:29 '  File "quest.py", line 1088, in complete\n    res = poe_bot.mover.goToPoint(\n'
2024-10-11T18:00:29 '  File "C:\\poe_bot\\1_host\\utils\\mover.py", line 459, in goToPoint\n    custom_break_function_result = custom_break_function(self)\n'
2024-10-11T18:00:29 '  File "quest.py", line 1048, in exploreRoutine\n    self.clearBossroom(bossroom_encounter)\n'
2024-10-11T18:00:29 '  File "quest.py", line 1251, in clearBossroom\n    self.onBossroomCompleteFunction()\n'
2024-10-11T18:00:29 '  File "quest.py", line 3008, in onBossroomCompleteFunction\n    poe_bot.raiseLongSleepException(\'supposed to have the key\')\n'
2024-10-11T18:00:29 '  File "C:\\poe_bot\\1_host\\utils\\gamehelper.py", line 351, in raiseLongSleepException\n    raiseLongSleepException(text)\n'
2024-10-11T18:00:29 '  File "C:\\poe_bot\\1_host\\utils\\utils.py", line 108, in raiseLongSleepException\n    raise Exception(f\'{text} , sleep 3600*24\')\n'
2024-10-11T18:03:55 exceptions must derive from BaseException
2024-10-11T18:03:55 exceptions must derive from BaseException
2024-10-11T18:03:55 '  File "quest.py", line 4735, in <module>\n    current_quest_area.complete()\n'
2024-10-11T18:03:55 '  File "quest.py", line 1183, in complete\n    raise "completed"\n'
2024-10-11T18:05:00 #resurrectAtCheckpoint call 1728641100.0559103
2024-10-11T18:17:29 #resurrectAtCheckpoint call 1728641849.4418218
2024-10-11T18:17:53 #resurrectAtCheckpoint call 1728641873.3992658
2024-10-11T18:18:09 #resurrectAtCheckpoint call 1728641889.1946573
2024-10-11T18:18:33 #resurrectAtCheckpoint call 1728641913.62666
2024-10-11T18:18:47 #resurrectAtCheckpoint call 1728641927.692648
2024-10-11T18:19:07 #resurrectAtCheckpoint call 1728641947.9870784
2024-10-11T18:20:23 #resurrectAtCheckpoint call 1728642023.539869
2024-10-11T18:20:39 #resurrectAtCheckpoint call 1728642039.4603057
2024-10-11T18:28:41 1_4_town current area isn't supported
2024-10-11T18:28:41 1_4_town current area isn't supported
2024-10-11T18:28:41 '  File "quest.py", line 4734, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-10-11T18:28:41 '  File "quest.py", line 4724, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-10-11T18:28:43 1_4_town current area isn't supported
2024-10-11T18:28:43 1_4_town current area isn't supported
2024-10-11T18:28:44 '  File "quest.py", line 4734, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-10-11T18:28:44 '  File "quest.py", line 4724, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-10-11T18:28:46 1_4_town current area isn't supported
2024-10-11T18:28:46 1_4_town current area isn't supported
2024-10-11T18:28:46 '  File "quest.py", line 4734, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-10-11T18:28:46 '  File "quest.py", line 4724, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-10-11T18:28:48 1_4_town current area isn't supported
2024-10-11T18:28:48 1_4_town current area isn't supported
2024-10-11T18:28:48 '  File "quest.py", line 4734, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-10-11T18:28:48 '  File "quest.py", line 4724, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-10-11T18:28:51 1_4_town current area isn't supported
2024-10-11T18:28:51 1_4_town current area isn't supported
2024-10-11T18:28:51 '  File "quest.py", line 4734, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-10-11T18:28:51 '  File "quest.py", line 4724, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-10-11T18:28:54 1_4_town current area isn't supported
2024-10-11T18:28:54 1_4_town current area isn't supported
2024-10-11T18:28:54 '  File "quest.py", line 4734, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-10-11T18:28:54 '  File "quest.py", line 4724, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-10-11T18:28:57 1_4_town current area isn't supported
2024-10-11T18:28:57 1_4_town current area isn't supported
2024-10-11T18:28:57 '  File "quest.py", line 4734, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-10-11T18:28:57 '  File "quest.py", line 4724, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-10-11T18:28:59 1_4_town current area isn't supported
2024-10-11T18:28:59 1_4_town current area isn't supported
2024-10-11T18:28:59 '  File "quest.py", line 4734, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-10-11T18:28:59 '  File "quest.py", line 4724, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-10-11T18:29:04 1_4_town current area isn't supported
2024-10-11T18:29:04 1_4_town current area isn't supported
2024-10-11T18:29:04 '  File "quest.py", line 4734, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-10-11T18:29:04 '  File "quest.py", line 4724, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-10-11T18:29:06 1_4_town current area isn't supported
2024-10-11T18:29:06 1_4_town current area isn't supported
2024-10-11T18:29:06 '  File "quest.py", line 4734, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-10-11T18:29:06 '  File "quest.py", line 4724, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-10-11T18:29:09 1_4_town current area isn't supported
2024-10-11T18:29:09 1_4_town current area isn't supported
2024-10-11T18:29:09 '  File "quest.py", line 4734, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-10-11T18:29:09 '  File "quest.py", line 4724, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-10-11T18:29:12 1_4_town current area isn't supported
2024-10-11T18:29:12 1_4_town current area isn't supported
2024-10-11T18:29:12 '  File "quest.py", line 4734, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-10-11T18:29:12 '  File "quest.py", line 4724, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-10-11T18:32:22 #resurrectAtCheckpoint call 1728642742.0125973
2024-10-11T18:36:06 #resurrectAtCheckpoint call 1728642966.1982496
2024-10-11T18:37:31 list index out of range
2024-10-11T18:37:31 list index out of range
2024-10-11T18:37:31 '  File "quest.py", line 742, in <module>\n    poe_bot.game_data.terrain.getCurrentlyPassableArea()\n'
2024-10-11T18:37:31 '  File "C:\\poe_bot\\1_host\\utils\\gamehelper.py", line 503, in getCurrentlyPassableArea\n    nearest_passable_player_point = list(list(zip(nearest_passable_player_points[0], nearest_passable_player_points[1]))[0])\n'
2024-10-11T18:40:49 1_4_5_1 current area isn't supported
2024-10-11T18:40:49 1_4_5_1 current area isn't supported
2024-10-11T18:40:49 '  File "quest.py", line 4734, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-10-11T18:40:49 '  File "quest.py", line 4724, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-10-11T18:46:27 1_4_5_1 current area isn't supported
2024-10-11T18:46:27 1_4_5_1 current area isn't supported
2024-10-11T18:46:27 '  File "quest.py", line 4734, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-10-11T18:46:27 '  File "quest.py", line 4724, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-10-11T18:46:30 1_4_5_1 current area isn't supported
2024-10-11T18:46:30 1_4_5_1 current area isn't supported
2024-10-11T18:46:30 '  File "quest.py", line 4734, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-10-11T18:46:30 '  File "quest.py", line 4724, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-10-11T18:46:33 1_4_5_1 current area isn't supported
2024-10-11T18:46:33 1_4_5_1 current area isn't supported
2024-10-11T18:46:33 '  File "quest.py", line 4734, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-10-11T18:46:33 '  File "quest.py", line 4724, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-10-11T18:46:36 1_4_5_1 current area isn't supported
2024-10-11T18:46:36 1_4_5_1 current area isn't supported
2024-10-11T18:46:36 '  File "quest.py", line 4734, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-10-11T18:46:36 '  File "quest.py", line 4724, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-10-11T18:46:39 1_4_5_1 current area isn't supported
2024-10-11T18:46:39 1_4_5_1 current area isn't supported
2024-10-11T18:46:39 '  File "quest.py", line 4734, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-10-11T18:46:39 '  File "quest.py", line 4724, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-10-11T18:58:37 #resurrectAtCheckpoint call 1728644317.0739014
2024-10-11T18:59:07 #resurrectAtCheckpoint call 1728644347.8901765
2024-10-11T18:59:36 #resurrectAtCheckpoint call 1728644376.7741067
2024-10-11T18:59:53 #resurrectAtCheckpoint call 1728644393.0090284
2024-10-11T19:00:04 #resurrectAtCheckpoint call 1728644404.104442
2024-10-11T19:00:48 #resurrectAtCheckpoint call 1728644448.3789222
2024-10-11T19:17:29 #resurrectAtCheckpoint call 1728645449.747038
2024-10-11T19:20:58 1_5_town current area isn't supported
2024-10-11T19:20:58 1_5_town current area isn't supported
2024-10-11T19:20:58 '  File "quest.py", line 4734, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-10-11T19:20:58 '  File "quest.py", line 4724, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-10-11T19:21:00 1_5_town current area isn't supported
2024-10-11T19:21:00 1_5_town current area isn't supported
2024-10-11T19:21:00 '  File "quest.py", line 4734, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-10-11T19:21:00 '  File "quest.py", line 4724, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-10-11T19:21:03 1_5_town current area isn't supported
2024-10-11T19:21:03 1_5_town current area isn't supported
2024-10-11T19:21:03 '  File "quest.py", line 4734, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-10-11T19:21:03 '  File "quest.py", line 4724, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-10-11T19:21:06 1_5_town current area isn't supported
2024-10-11T19:21:06 1_5_town current area isn't supported
2024-10-11T19:21:06 '  File "quest.py", line 4734, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-10-11T19:21:06 '  File "quest.py", line 4724, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-10-11T19:21:08 1_5_town current area isn't supported
2024-10-11T19:21:08 1_5_town current area isn't supported
2024-10-11T19:21:08 '  File "quest.py", line 4734, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-10-11T19:21:08 '  File "quest.py", line 4724, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-10-11T19:21:10 1_5_town current area isn't supported
2024-10-11T19:21:10 1_5_town current area isn't supported
2024-10-11T19:21:10 '  File "quest.py", line 4734, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-10-11T19:21:10 '  File "quest.py", line 4724, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-10-11T19:21:13 1_5_town current area isn't supported
2024-10-11T19:21:13 1_5_town current area isn't supported
2024-10-11T19:21:13 '  File "quest.py", line 4734, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-10-11T19:21:13 '  File "quest.py", line 4724, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-10-11T19:21:15 1_5_town current area isn't supported
2024-10-11T19:21:15 1_5_town current area isn't supported
2024-10-11T19:21:15 '  File "quest.py", line 4734, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-10-11T19:21:15 '  File "quest.py", line 4724, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-10-11T19:21:18 1_5_town current area isn't supported
2024-10-11T19:21:18 1_5_town current area isn't supported
2024-10-11T19:21:18 '  File "quest.py", line 4734, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-10-11T19:21:18 '  File "quest.py", line 4724, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-10-11T19:21:20 1_5_town current area isn't supported
2024-10-11T19:21:20 1_5_town current area isn't supported
2024-10-11T19:21:20 '  File "quest.py", line 4734, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-10-11T19:21:20 '  File "quest.py", line 4724, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-10-11T19:21:22 1_5_town current area isn't supported
2024-10-11T19:21:22 1_5_town current area isn't supported
2024-10-11T19:21:22 '  File "quest.py", line 4734, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-10-11T19:21:22 '  File "quest.py", line 4724, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-10-11T19:21:24 1_5_town current area isn't supported
2024-10-11T19:21:24 1_5_town current area isn't supported
2024-10-11T19:21:24 '  File "quest.py", line 4734, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-10-11T19:21:24 '  File "quest.py", line 4724, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-10-11T19:21:26 1_5_town current area isn't supported
2024-10-11T19:21:26 1_5_town current area isn't supported
2024-10-11T19:21:26 '  File "quest.py", line 4734, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-10-11T19:21:26 '  File "quest.py", line 4724, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-10-11T19:21:29 1_5_town current area isn't supported
2024-10-11T19:21:29 1_5_town current area isn't supported
2024-10-11T19:21:29 '  File "quest.py", line 4734, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-10-11T19:21:29 '  File "quest.py", line 4724, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-10-11T19:21:31 1_5_town current area isn't supported
2024-10-11T19:21:31 1_5_town current area isn't supported
2024-10-11T19:21:31 '  File "quest.py", line 4734, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-10-11T19:21:31 '  File "quest.py", line 4724, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-10-11T19:21:33 1_5_town current area isn't supported
2024-10-11T19:21:33 1_5_town current area isn't supported
2024-10-11T19:21:33 '  File "quest.py", line 4734, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-10-11T19:21:33 '  File "quest.py", line 4724, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-10-11T19:21:35 1_5_town current area isn't supported
2024-10-11T19:21:35 1_5_town current area isn't supported
2024-10-11T19:21:35 '  File "quest.py", line 4734, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-10-11T19:21:35 '  File "quest.py", line 4724, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-10-11T19:21:37 1_5_town current area isn't supported
2024-10-11T19:21:37 1_5_town current area isn't supported
2024-10-11T19:21:37 '  File "quest.py", line 4734, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-10-11T19:21:37 '  File "quest.py", line 4724, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-10-11T19:21:40 1_5_town current area isn't supported
2024-10-11T19:21:40 1_5_town current area isn't supported
2024-10-11T19:21:40 '  File "quest.py", line 4734, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-10-11T19:21:40 '  File "quest.py", line 4724, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-10-11T19:21:42 1_5_town current area isn't supported
2024-10-11T19:21:42 1_5_town current area isn't supported
2024-10-11T19:21:42 '  File "quest.py", line 4734, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-10-11T19:21:42 '  File "quest.py", line 4724, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-10-11T19:21:44 1_5_town current area isn't supported
2024-10-11T19:21:44 1_5_town current area isn't supported
2024-10-11T19:21:44 '  File "quest.py", line 4734, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-10-11T19:21:44 '  File "quest.py", line 4724, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-10-11T19:21:46 1_5_town current area isn't supported
2024-10-11T19:21:46 1_5_town current area isn't supported
2024-10-11T19:21:46 '  File "quest.py", line 4734, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-10-11T19:21:46 '  File "quest.py", line 4724, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-10-11T19:21:49 1_5_town current area isn't supported
2024-10-11T19:21:49 1_5_town current area isn't supported
2024-10-11T19:21:49 '  File "quest.py", line 4734, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-10-11T19:21:49 '  File "quest.py", line 4724, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-10-11T19:23:34 #resurrectAtCheckpoint call 1728645814.4902754
2024-10-11T19:24:46 #resurrectAtCheckpoint call 1728645886.4715092
2024-10-11T19:26:05 #resurrectAtCheckpoint call 1728645965.8449202
2024-10-11T19:29:44 #resurrectAtCheckpoint call 1728646184.454117
2024-10-11T19:31:37 #resurrectAtCheckpoint call 1728646297.7749505
2024-10-11T19:36:11 #resurrectAtCheckpoint call 1728646571.462008
2024-10-11T19:40:59 exceptions must derive from BaseException
2024-10-11T19:40:59 exceptions must derive from BaseException
2024-10-11T19:40:59 '  File "quest.py", line 4735, in <module>\n    current_quest_area.complete()\n'
2024-10-11T19:40:59 '  File "quest.py", line 1183, in complete\n    raise "completed"\n'
2024-10-11T19:46:45 #resurrectAtCheckpoint call 1728647205.079031
2024-10-11T19:51:57 #resurrectAtCheckpoint call 1728647517.2854457
2024-10-11T19:54:06 #resurrectAtCheckpoint call 1728647646.6426816
2024-10-11T19:56:17 #resurrectAtCheckpoint call 1728647777.4096859
2024-10-11T19:59:07 #resurrectAtCheckpoint call 1728647947.473926
2024-10-11T20:03:51 #resurrectAtCheckpoint call 1728648231.8494194
2024-10-11T20:05:10 exceptions must derive from BaseException
2024-10-11T20:05:10 exceptions must derive from BaseException
2024-10-11T20:05:10 '  File "quest.py", line 4735, in <module>\n    current_quest_area.complete()\n'
2024-10-11T20:05:10 '  File "quest.py", line 1183, in complete\n    raise "completed"\n'
2024-10-11T20:14:34 list index out of range
2024-10-11T20:14:34 list index out of range
2024-10-11T20:14:34 '  File "quest.py", line 742, in <module>\n    poe_bot.game_data.terrain.getCurrentlyPassableArea()\n'
2024-10-11T20:14:34 '  File "C:\\poe_bot\\1_host\\utils\\gamehelper.py", line 503, in getCurrentlyPassableArea\n    nearest_passable_player_point = list(list(zip(nearest_passable_player_points[0], nearest_passable_player_points[1]))[0])\n'
2024-10-11T20:17:49 exceptions must derive from BaseException
2024-10-11T20:17:49 exceptions must derive from BaseException
2024-10-11T20:17:49 '  File "quest.py", line 4735, in <module>\n    current_quest_area.complete()\n'
2024-10-11T20:17:49 '  File "quest.py", line 1183, in complete\n    raise "completed"\n'
2024-10-11T20:28:27 exceptions must derive from BaseException
2024-10-11T20:28:27 exceptions must derive from BaseException
2024-10-11T20:28:27 '  File "quest.py", line 4735, in <module>\n    current_quest_area.complete()\n'
2024-10-11T20:28:27 '  File "quest.py", line 1183, in complete\n    raise "completed"\n'
2024-10-11T20:37:50 #resurrectAtCheckpoint call 1728650270.6130426
2024-10-11T20:38:41 #resurrectAtCheckpoint call 1728650321.3597722
2024-10-11T20:40:10 #resurrectAtCheckpoint call 1728650410.0684197
2024-10-11T20:40:40 #resurrectAtCheckpoint call 1728650440.145697
2024-10-11T20:41:23 #resurrectAtCheckpoint call 1728650483.7641723
2024-10-11T20:41:40 #resurrectAtCheckpoint call 1728650500.0285459
2024-10-11T20:43:08 #resurrectAtCheckpoint call 1728650588.2586815
2024-10-11T20:47:48 2_6_1 current area isn't supported
2024-10-11T20:47:48 2_6_1 current area isn't supported
2024-10-11T20:47:48 '  File "quest.py", line 4734, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-10-11T20:47:48 '  File "quest.py", line 4724, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-10-11T20:56:40 #resurrectAtCheckpoint call 1728651400.1213796
2024-10-11T20:57:36 #resurrectAtCheckpoint call 1728651456.407944
2024-10-11T20:59:51 list index out of range
2024-10-11T20:59:51 list index out of range
2024-10-11T20:59:51 '  File "quest.py", line 742, in <module>\n    poe_bot.game_data.terrain.getCurrentlyPassableArea()\n'
2024-10-11T20:59:51 '  File "C:\\poe_bot\\1_host\\utils\\gamehelper.py", line 503, in getCurrentlyPassableArea\n    nearest_passable_player_point = list(list(zip(nearest_passable_player_points[0], nearest_passable_player_points[1]))[0])\n'
2024-10-11T21:02:07 #resurrectAtCheckpoint call 1728651727.425528
2024-10-11T21:30:02 #resurrectAtCheckpoint call 1728653402.4644954
2024-10-11T21:30:27 #resurrectAtCheckpoint call 1728653427.6560428
2024-10-11T21:57:16 #resurrectAtCheckpoint call 1728655036.7949018
2024-10-11T22:04:52 exceptions must derive from BaseException
2024-10-11T22:04:52 exceptions must derive from BaseException
2024-10-11T22:04:52 '  File "quest.py", line 4735, in <module>\n    current_quest_area.complete()\n'
2024-10-11T22:04:52 '  File "quest.py", line 1183, in complete\n    raise "completed"\n'
2024-10-11T22:09:35 #resurrectAtCheckpoint call 1728655775.6478562
2024-10-11T22:10:27 #resurrectAtCheckpoint call 1728655827.5265434
2024-10-11T22:11:11 #resurrectAtCheckpoint call 1728655871.4119568
2024-10-11T22:11:47 #resurrectAtCheckpoint call 1728655907.275514
2024-10-11T22:15:17 #resurrectAtCheckpoint call 1728656117.9168723
2024-10-11T22:20:34 #resurrectAtCheckpoint call 1728656434.4355402
2024-10-11T22:27:34 #resurrectAtCheckpoint call 1728656854.3047678
2024-10-11T22:39:18 list index out of range
2024-10-11T22:39:18 list index out of range
2024-10-11T22:39:18 '  File "quest.py", line 742, in <module>\n    poe_bot.game_data.terrain.getCurrentlyPassableArea()\n'
2024-10-11T22:39:18 '  File "C:\\poe_bot\\1_host\\utils\\gamehelper.py", line 503, in getCurrentlyPassableArea\n    nearest_passable_player_point = list(list(zip(nearest_passable_player_points[0], nearest_passable_player_points[1]))[0])\n'
2024-10-11T22:44:32 exceptions must derive from BaseException
2024-10-11T22:44:32 exceptions must derive from BaseException
2024-10-11T22:44:32 '  File "quest.py", line 4735, in <module>\n    current_quest_area.complete()\n'
2024-10-11T22:44:32 '  File "quest.py", line 1183, in complete\n    raise "completed"\n'
2024-10-11T22:47:00 relogging through char select screen
2024-10-11T22:47:01 getting to char selection screen from game
2024-10-11T22:47:51 2_7_town current area isn't supported
2024-10-11T22:47:51 2_7_town current area isn't supported
2024-10-11T22:47:51 '  File "quest.py", line 4734, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-10-11T22:47:51 '  File "quest.py", line 4724, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-10-11T22:47:58 2_7_town current area isn't supported
2024-10-11T22:47:58 2_7_town current area isn't supported
2024-10-11T22:47:58 '  File "quest.py", line 4734, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-10-11T22:47:58 '  File "quest.py", line 4724, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-10-11T23:03:46 #resurrectAtCheckpoint call 1728659026.7029092
2024-10-11T23:17:39 #resurrectAtCheckpoint call 1728659859.784833
2024-10-11T23:20:33 exceptions must derive from BaseException
2024-10-11T23:20:33 exceptions must derive from BaseException
2024-10-11T23:20:33 '  File "quest.py", line 4735, in <module>\n    current_quest_area.complete()\n'
2024-10-11T23:20:33 '  File "quest.py", line 1183, in complete\n    raise "completed"\n'
2024-10-11T23:35:05 #resurrectAtCheckpoint call 1728660905.6295743
2024-10-11T23:39:06 #resurrectAtCheckpoint call 1728661146.526245
2024-10-11T23:42:07 'NoneType' object is not callable
2024-10-11T23:42:07 'NoneType' object is not callable
2024-10-11T23:42:07 '  File "quest.py", line 741, in <module>\n    poe_bot.refreshAll()\n'
2024-10-11T23:42:07 '  File "C:\\poe_bot\\1_host\\utils\\gamehelper.py", line 245, in refreshAll\n    refreshed_data = self.getData(request_type="full")\n'
2024-10-11T23:42:07 '  File "C:\\poe_bot\\1_host\\utils\\gamehelper.py", line 192, in getData\n    self.relogRestartSetActive()\n'
2024-10-11T23:42:07 '  File "C:\\poe_bot\\1_host\\utils\\gamehelper.py", line 172, in relogRestartSetActive\n    self.on_disconnect_function()\n'
2024-10-11T23:42:40 2_8_town current area isn't supported
2024-10-11T23:42:40 2_8_town current area isn't supported
2024-10-11T23:42:40 '  File "quest.py", line 4746, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-10-11T23:42:40 '  File "quest.py", line 4736, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-10-11T23:42:43 2_8_town current area isn't supported
2024-10-11T23:42:43 2_8_town current area isn't supported
2024-10-11T23:42:43 '  File "quest.py", line 4746, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-10-11T23:42:43 '  File "quest.py", line 4736, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-10-11T23:42:46 2_8_town current area isn't supported
2024-10-11T23:42:46 2_8_town current area isn't supported
2024-10-11T23:42:46 '  File "quest.py", line 4746, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-10-11T23:42:46 '  File "quest.py", line 4736, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-10-11T23:42:50 2_8_town current area isn't supported
2024-10-11T23:42:50 2_8_town current area isn't supported
2024-10-11T23:42:50 '  File "quest.py", line 4746, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-10-11T23:42:50 '  File "quest.py", line 4736, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-10-11T23:42:54 2_8_town current area isn't supported
2024-10-11T23:42:54 2_8_town current area isn't supported
2024-10-11T23:42:54 '  File "quest.py", line 4746, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-10-11T23:42:54 '  File "quest.py", line 4736, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-10-11T23:42:58 2_8_town current area isn't supported
2024-10-11T23:42:58 2_8_town current area isn't supported
2024-10-11T23:42:58 '  File "quest.py", line 4746, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-10-11T23:42:58 '  File "quest.py", line 4736, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-10-11T23:43:02 2_8_town current area isn't supported
2024-10-11T23:43:02 2_8_town current area isn't supported
2024-10-11T23:43:02 '  File "quest.py", line 4746, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-10-11T23:43:02 '  File "quest.py", line 4736, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-10-11T23:43:06 2_8_town current area isn't supported
2024-10-11T23:43:06 2_8_town current area isn't supported
2024-10-11T23:43:06 '  File "quest.py", line 4746, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-10-11T23:43:06 '  File "quest.py", line 4736, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-10-11T23:45:07 2_8_2_2 current area isn't supported
2024-10-11T23:45:07 2_8_2_2 current area isn't supported
2024-10-11T23:45:07 '  File "quest.py", line 4746, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-10-11T23:45:07 '  File "quest.py", line 4736, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-10-11T23:45:11 2_8_2_2 current area isn't supported
2024-10-11T23:45:11 2_8_2_2 current area isn't supported
2024-10-11T23:45:11 '  File "quest.py", line 4746, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-10-11T23:45:11 '  File "quest.py", line 4736, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-10-11T23:45:16 2_8_2_2 current area isn't supported
2024-10-11T23:45:16 2_8_2_2 current area isn't supported
2024-10-11T23:45:16 '  File "quest.py", line 4746, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-10-11T23:45:16 '  File "quest.py", line 4736, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-10-11T23:45:19 2_8_2_2 current area isn't supported
2024-10-11T23:45:19 2_8_2_2 current area isn't supported
2024-10-11T23:45:19 '  File "quest.py", line 4746, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-10-11T23:45:19 '  File "quest.py", line 4736, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-10-11T23:45:24 2_8_2_2 current area isn't supported
2024-10-11T23:45:24 2_8_2_2 current area isn't supported
2024-10-11T23:45:24 '  File "quest.py", line 4746, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-10-11T23:45:24 '  File "quest.py", line 4736, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-10-11T23:45:27 2_8_2_2 current area isn't supported
2024-10-11T23:45:27 2_8_2_2 current area isn't supported
2024-10-11T23:45:27 '  File "quest.py", line 4746, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-10-11T23:45:27 '  File "quest.py", line 4736, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-10-11T23:45:34 2_8_2_2 current area isn't supported
2024-10-11T23:45:34 2_8_2_2 current area isn't supported
2024-10-11T23:45:34 '  File "quest.py", line 4746, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-10-11T23:45:34 '  File "quest.py", line 4736, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-10-11T23:45:37 2_8_2_2 current area isn't supported
2024-10-11T23:45:37 2_8_2_2 current area isn't supported
2024-10-11T23:45:37 '  File "quest.py", line 4746, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-10-11T23:45:37 '  File "quest.py", line 4736, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
