2024-11-10T18:42:57 #resurrectAtCheckpoint call 1731235377.5232632
2024-11-10T20:26:00 #resurrectAtCheckpoint call 1731241560.9787295
2024-11-10T20:27:52 #resurrectAtCheckpoint call 1731241672.4200451
2024-11-10T20:35:23 #resurrectAtCheckpoint call 1731242123.5365195
2024-11-10T20:35:38 #resurrectAtCheckpoint call 1731242138.0117188
2024-11-10T20:37:28 #resurrectAtCheckpoint call 1731242248.9575615
2024-11-10T20:37:58 #resurrectAtCheckpoint call 1731242278.9175308
2024-11-10T20:38:13 #resurrectAtCheckpoint call 1731242293.5043883
2024-11-10T20:38:45 #resurrectAtCheckpoint call 1731242325.0528965
2024-11-10T20:43:15 
2024-11-10T20:43:15 '  File "quest.py", line 4875, in <module>\n    current_quest_area.complete()\n'
2024-11-10T20:43:15 '  File "quest.py", line 1148, in complete\n    res = poe_bot.mover.goToPoint(\n'
2024-11-10T20:43:15 '  File "D:\\poe_bot\\1_host\\utils\\mover.py", line 345, in goToPoint\n    custom_break_function_result = custom_break_function(self)\n'
2024-11-10T20:43:15 '  File "quest.py", line 1108, in exploreRoutine\n    self.clearBossroom(bossroom_encounter)\n'
2024-11-10T20:43:15 '  File "quest.py", line 3977, in clearBossroom\n    bossroom_encounter.clearBossroom()\n'
2024-11-10T20:43:15 '  File "D:\\poe_bot\\1_host\\utils\\encounters.py", line 206, in clearBossroom\n    res = mover.goToPoint(\n'
2024-11-10T20:43:15 '  File "D:\\poe_bot\\1_host\\utils\\mover.py", line 504, in goToPoint\n    custom_break_function_result = custom_break_function(self)\n'
2024-11-10T20:43:15 '  File "D:\\poe_bot\\1_host\\utils\\encounters.py", line 188, in custom_break_function_nested\n    res = self.clear_room_custom_break_function(self.poe_bot.mover)\n'
2024-11-10T20:43:15 '  File "quest.py", line 3972, in lookForWardensChambers\n    next((ch for ch in poe_bot.ui.npc_dialogue.choices if ch.text == "Sail to the Bridge Encampment")).click()\n'
2024-11-10T22:28:12 relogging through char select screen
2024-11-10T22:28:12 getting to char selection screen from game
2024-11-10T22:28:43 2_7_town current area isn't supported
2024-11-10T22:28:43 '  File "quest.py", line 4866, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-11-10T22:28:43 '  File "quest.py", line 4856, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-11-10T22:28:46 2_7_town current area isn't supported
2024-11-10T22:28:46 '  File "quest.py", line 4866, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-11-10T22:28:46 '  File "quest.py", line 4856, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-11-10T22:28:49 2_7_town current area isn't supported
2024-11-10T22:28:49 '  File "quest.py", line 4866, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-11-10T22:28:49 '  File "quest.py", line 4856, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-11-10T22:28:51 2_7_town current area isn't supported
2024-11-10T22:28:51 '  File "quest.py", line 4866, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-11-10T22:28:51 '  File "quest.py", line 4856, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-11-10T22:28:55 2_7_town current area isn't supported
2024-11-10T22:28:55 '  File "quest.py", line 4866, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-11-10T22:28:55 '  File "quest.py", line 4856, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
