2024-12-16T13:42:17 #resurrectAtCheckpoint call 1734327737.7753444
2024-12-16T13:45:59 #resurrectAtCheckpoint call 1734327959.508763
2024-12-16T13:50:58 #resurrectAtCheckpoint call 1734328258.3376071
2024-12-16T18:43:50 exceptions must derive from BaseException
2024-12-16T18:43:50 '  File "poe_2_lost_city.py", line 468, in <module>\n    raise 404\n'
2024-12-16T18:43:56 exceptions must derive from BaseException
2024-12-16T18:43:56 '  File "poe_2_lost_city.py", line 468, in <module>\n    raise 404\n'
2024-12-16T18:44:15 exceptions must derive from BaseException
2024-12-16T18:44:15 '  File "poe_2_lost_city.py", line 468, in <module>\n    raise 404\n'
2024-12-16T18:48:07 exceptions must derive from BaseException
2024-12-16T18:48:07 '  File "poe_2_lost_city.py", line 469, in <module>\n    raise 404\n'
2024-12-16T18:48:12 exceptions must derive from BaseException
2024-12-16T18:48:12 '  File "poe_2_lost_city.py", line 469, in <module>\n    raise 404\n'
2024-12-16T18:48:27 exceptions must derive from BaseException
2024-12-16T18:48:27 '  File "poe_2_lost_city.py", line 469, in <module>\n    raise 404\n'
2024-12-16T18:55:56 exceptions must derive from BaseException
2024-12-16T18:55:56 '  File "poe_2_lost_city.py", line 474, in <module>\n    raise 404\n'
2024-12-16T18:56:26 exceptions must derive from BaseException
2024-12-16T18:56:26 '  File "poe_2_lost_city.py", line 474, in <module>\n    raise 404\n'
2024-12-16T18:56:47 exceptions must derive from BaseException
2024-12-16T18:56:47 '  File "poe_2_lost_city.py", line 474, in <module>\n    raise 404\n'
2024-12-16T18:57:26 exceptions must derive from BaseException
2024-12-16T18:57:26 '  File "poe_2_lost_city.py", line 474, in <module>\n    raise 404\n'
2024-12-16T18:57:50 exceptions must derive from BaseException
2024-12-16T18:57:50 '  File "poe_2_lost_city.py", line 474, in <module>\n    raise 404\n'
2024-12-16T18:58:10 exceptions must derive from BaseException
2024-12-16T18:58:10 '  File "poe_2_lost_city.py", line 474, in <module>\n    raise 404\n'
2024-12-16T18:58:32 exceptions must derive from BaseException
2024-12-16T18:58:32 '  File "poe_2_lost_city.py", line 474, in <module>\n    raise 404\n'
2024-12-16T18:58:56 exceptions must derive from BaseException
2024-12-16T18:58:56 '  File "poe_2_lost_city.py", line 474, in <module>\n    raise 404\n'
2024-12-16T18:59:17 exceptions must derive from BaseException
2024-12-16T18:59:17 '  File "poe_2_lost_city.py", line 474, in <module>\n    raise 404\n'
2024-12-16T18:59:40 exceptions must derive from BaseException
2024-12-16T18:59:40 '  File "poe_2_lost_city.py", line 474, in <module>\n    raise 404\n'
2024-12-16T19:00:10 exceptions must derive from BaseException
2024-12-16T19:00:10 '  File "poe_2_lost_city.py", line 474, in <module>\n    raise 404\n'
2024-12-16T19:00:23 exceptions must derive from BaseException
2024-12-16T19:00:23 '  File "poe_2_lost_city.py", line 474, in <module>\n    raise 404\n'
2024-12-16T19:00:52 exceptions must derive from BaseException
2024-12-16T19:00:52 '  File "poe_2_lost_city.py", line 474, in <module>\n    raise 404\n'
2024-12-16T19:01:18 exceptions must derive from BaseException
2024-12-16T19:01:18 '  File "poe_2_lost_city.py", line 474, in <module>\n    raise 404\n'
2024-12-16T19:01:40 exceptions must derive from BaseException
2024-12-16T19:01:40 '  File "poe_2_lost_city.py", line 474, in <module>\n    raise 404\n'
2024-12-16T20:17:30 'Backend' object has no attribute 'last_data'
2024-12-16T20:17:30 '  File "poe_2_lost_city.py", line 458, in <module>\n    poe_bot.loot_picker.collectLootWhilePresented()\n'
2024-12-16T20:17:30 '  File "C:\\p2\\1_host\\utils\\loot_filter.py", line 105, in collectLootWhilePresented\n    loot_collected = self.collectLoot()\n'
2024-12-16T20:17:30 '  File "C:\\p2\\1_host\\utils\\loot_filter.py", line 52, in collectLoot\n    pickable_items = poe_bot.loot_picker.loot_filter.getPickableItems()\n'
2024-12-16T20:17:30 '  File "C:\\p2\\1_host\\utils\\loot_filter.py", line 310, in getPickableItems\n    item_visible_labels = poe_bot.backend.last_data[\'i\'].copy()\n'
2024-12-16T20:17:31 'Backend' object has no attribute 'last_data'
2024-12-16T20:17:31 '  File "poe_2_lost_city.py", line 458, in <module>\n    poe_bot.loot_picker.collectLootWhilePresented()\n'
2024-12-16T20:17:31 '  File "C:\\p2\\1_host\\utils\\loot_filter.py", line 105, in collectLootWhilePresented\n    loot_collected = self.collectLoot()\n'
2024-12-16T20:17:31 '  File "C:\\p2\\1_host\\utils\\loot_filter.py", line 52, in collectLoot\n    pickable_items = poe_bot.loot_picker.loot_filter.getPickableItems()\n'
2024-12-16T20:17:31 '  File "C:\\p2\\1_host\\utils\\loot_filter.py", line 310, in getPickableItems\n    item_visible_labels = poe_bot.backend.last_data[\'i\'].copy()\n'
2024-12-16T20:17:33 'Backend' object has no attribute 'last_data'
2024-12-16T20:17:33 '  File "poe_2_lost_city.py", line 458, in <module>\n    poe_bot.loot_picker.collectLootWhilePresented()\n'
2024-12-16T20:17:33 '  File "C:\\p2\\1_host\\utils\\loot_filter.py", line 105, in collectLootWhilePresented\n    loot_collected = self.collectLoot()\n'
2024-12-16T20:17:33 '  File "C:\\p2\\1_host\\utils\\loot_filter.py", line 52, in collectLoot\n    pickable_items = poe_bot.loot_picker.loot_filter.getPickableItems()\n'
2024-12-16T20:17:33 '  File "C:\\p2\\1_host\\utils\\loot_filter.py", line 310, in getPickableItems\n    item_visible_labels = poe_bot.backend.last_data[\'i\'].copy()\n'
2024-12-16T20:24:01 exceptions must derive from BaseException
2024-12-16T20:24:01 '  File "poe_2_lost_city.py", line 497, in <module>\n    raise 404\n'
2024-12-16T20:24:35 exceptions must derive from BaseException
2024-12-16T20:24:35 '  File "poe_2_lost_city.py", line 497, in <module>\n    raise 404\n'
2024-12-16T20:25:00 exceptions must derive from BaseException
2024-12-16T20:25:00 '  File "poe_2_lost_city.py", line 497, in <module>\n    raise 404\n'
2024-12-16T20:25:20 exceptions must derive from BaseException
2024-12-16T20:25:20 '  File "poe_2_lost_city.py", line 497, in <module>\n    raise 404\n'
2024-12-16T20:25:48 exceptions must derive from BaseException
2024-12-16T20:25:48 '  File "poe_2_lost_city.py", line 497, in <module>\n    raise 404\n'
2024-12-16T20:26:09 exceptions must derive from BaseException
2024-12-16T20:26:09 '  File "poe_2_lost_city.py", line 497, in <module>\n    raise 404\n'
2024-12-16T20:26:28 exceptions must derive from BaseException
2024-12-16T20:26:28 '  File "poe_2_lost_city.py", line 497, in <module>\n    raise 404\n'
2024-12-16T20:26:57 exceptions must derive from BaseException
2024-12-16T20:26:57 '  File "poe_2_lost_city.py", line 497, in <module>\n    raise 404\n'
2024-12-16T20:27:17 exceptions must derive from BaseException
2024-12-16T20:27:17 '  File "poe_2_lost_city.py", line 497, in <module>\n    raise 404\n'
2024-12-16T20:27:27 #resurrectAtCheckpoint call 1734352047.0839388
2024-12-16T20:27:53 exceptions must derive from BaseException
2024-12-16T20:27:53 '  File "poe_2_lost_city.py", line 497, in <module>\n    raise 404\n'
2024-12-16T20:29:08 exceptions must derive from BaseException
2024-12-16T20:29:08 '  File "poe_2_lost_city.py", line 497, in <module>\n    raise 404\n'
2024-12-16T20:29:41 exceptions must derive from BaseException
2024-12-16T20:29:41 '  File "poe_2_lost_city.py", line 497, in <module>\n    raise 404\n'
2024-12-16T20:30:02 exceptions must derive from BaseException
2024-12-16T20:30:02 '  File "poe_2_lost_city.py", line 497, in <module>\n    raise 404\n'
2024-12-16T20:30:25 exceptions must derive from BaseException
2024-12-16T20:30:25 '  File "poe_2_lost_city.py", line 497, in <module>\n    raise 404\n'
2024-12-16T20:30:46 exceptions must derive from BaseException
2024-12-16T20:30:46 '  File "poe_2_lost_city.py", line 497, in <module>\n    raise 404\n'
2024-12-16T20:31:07 exceptions must derive from BaseException
2024-12-16T20:31:07 '  File "poe_2_lost_city.py", line 497, in <module>\n    raise 404\n'
2024-12-16T20:31:27 exceptions must derive from BaseException
2024-12-16T20:31:27 '  File "poe_2_lost_city.py", line 497, in <module>\n    raise 404\n'
2024-12-16T20:31:51 exceptions must derive from BaseException
2024-12-16T20:31:51 '  File "poe_2_lost_city.py", line 497, in <module>\n    raise 404\n'
2024-12-16T20:32:18 exceptions must derive from BaseException
2024-12-16T20:32:18 '  File "poe_2_lost_city.py", line 497, in <module>\n    raise 404\n'
2024-12-16T20:32:40 exceptions must derive from BaseException
2024-12-16T20:32:40 '  File "poe_2_lost_city.py", line 497, in <module>\n    raise 404\n'
2024-12-16T22:43:15 exceptions must derive from BaseException
2024-12-16T22:43:15 '  File "poe_2_lost_city.py", line 495, in <module>\n    raise 404\n'
2024-12-16T22:43:35 exceptions must derive from BaseException
2024-12-16T22:43:35 '  File "poe_2_lost_city.py", line 495, in <module>\n    raise 404\n'
2024-12-16T22:43:59 exceptions must derive from BaseException
2024-12-16T22:43:59 '  File "poe_2_lost_city.py", line 495, in <module>\n    raise 404\n'
2024-12-16T22:44:19 exceptions must derive from BaseException
2024-12-16T22:44:19 '  File "poe_2_lost_city.py", line 495, in <module>\n    raise 404\n'
2024-12-16T22:44:40 exceptions must derive from BaseException
2024-12-16T22:44:40 '  File "poe_2_lost_city.py", line 495, in <module>\n    raise 404\n'
2024-12-16T22:45:00 exceptions must derive from BaseException
2024-12-16T22:45:00 '  File "poe_2_lost_city.py", line 495, in <module>\n    raise 404\n'
2024-12-16T22:45:22 exceptions must derive from BaseException
2024-12-16T22:45:22 '  File "poe_2_lost_city.py", line 495, in <module>\n    raise 404\n'
2024-12-16T22:45:43 exceptions must derive from BaseException
2024-12-16T22:45:43 '  File "poe_2_lost_city.py", line 495, in <module>\n    raise 404\n'
2024-12-16T22:46:04 exceptions must derive from BaseException
2024-12-16T22:46:04 '  File "poe_2_lost_city.py", line 495, in <module>\n    raise 404\n'
2024-12-16T22:46:25 exceptions must derive from BaseException
2024-12-16T22:46:25 '  File "poe_2_lost_city.py", line 495, in <module>\n    raise 404\n'
2024-12-16T22:46:45 exceptions must derive from BaseException
2024-12-16T22:46:45 '  File "poe_2_lost_city.py", line 495, in <module>\n    raise 404\n'
2024-12-16T22:47:06 exceptions must derive from BaseException
2024-12-16T22:47:06 '  File "poe_2_lost_city.py", line 495, in <module>\n    raise 404\n'
2024-12-16T22:47:25 exceptions must derive from BaseException
2024-12-16T22:47:25 '  File "poe_2_lost_city.py", line 495, in <module>\n    raise 404\n'
2024-12-16T22:47:45 exceptions must derive from BaseException
2024-12-16T22:47:45 '  File "poe_2_lost_city.py", line 495, in <module>\n    raise 404\n'
2024-12-16T22:48:07 exceptions must derive from BaseException
2024-12-16T22:48:07 '  File "poe_2_lost_city.py", line 495, in <module>\n    raise 404\n'
2024-12-16T22:48:29 exceptions must derive from BaseException
2024-12-16T22:48:29 '  File "poe_2_lost_city.py", line 495, in <module>\n    raise 404\n'
2024-12-16T22:48:49 exceptions must derive from BaseException
2024-12-16T22:48:49 '  File "poe_2_lost_city.py", line 495, in <module>\n    raise 404\n'
2024-12-16T22:49:10 exceptions must derive from BaseException
2024-12-16T22:49:10 '  File "poe_2_lost_city.py", line 495, in <module>\n    raise 404\n'
2024-12-16T22:49:23 exceptions must derive from BaseException
2024-12-16T22:49:23 '  File "poe_2_lost_city.py", line 495, in <module>\n    raise 404\n'
2024-12-16T22:59:45 exceptions must derive from BaseException
2024-12-16T22:59:45 '  File "poe_2_lost_city.py", line 495, in <module>\n    raise 404\n'
2024-12-16T23:00:16 exceptions must derive from BaseException
2024-12-16T23:00:16 '  File "poe_2_lost_city.py", line 495, in <module>\n    raise 404\n'
2024-12-16T23:00:39 exceptions must derive from BaseException
2024-12-16T23:00:39 '  File "poe_2_lost_city.py", line 495, in <module>\n    raise 404\n'
2024-12-16T23:00:53 exceptions must derive from BaseException
2024-12-16T23:00:53 '  File "poe_2_lost_city.py", line 495, in <module>\n    raise 404\n'
2024-12-16T23:02:49 exceptions must derive from BaseException
2024-12-16T23:02:49 '  File "poe_2_lost_city.py", line 496, in <module>\n    raise 404\n'
2024-12-16T23:03:11 exceptions must derive from BaseException
2024-12-16T23:03:11 '  File "poe_2_lost_city.py", line 496, in <module>\n    raise 404\n'
2024-12-16T23:03:31 exceptions must derive from BaseException
2024-12-16T23:03:31 '  File "poe_2_lost_city.py", line 496, in <module>\n    raise 404\n'
2024-12-16T23:03:51 exceptions must derive from BaseException
2024-12-16T23:03:51 '  File "poe_2_lost_city.py", line 496, in <module>\n    raise 404\n'
2024-12-16T23:04:10 exceptions must derive from BaseException
2024-12-16T23:04:10 '  File "poe_2_lost_city.py", line 496, in <module>\n    raise 404\n'
2024-12-16T23:04:31 exceptions must derive from BaseException
2024-12-16T23:04:31 '  File "poe_2_lost_city.py", line 496, in <module>\n    raise 404\n'
2024-12-16T23:04:51 exceptions must derive from BaseException
2024-12-16T23:04:51 '  File "poe_2_lost_city.py", line 496, in <module>\n    raise 404\n'
2024-12-16T23:05:11 exceptions must derive from BaseException
2024-12-16T23:05:11 '  File "poe_2_lost_city.py", line 496, in <module>\n    raise 404\n'
2024-12-16T23:05:31 exceptions must derive from BaseException
2024-12-16T23:05:31 '  File "poe_2_lost_city.py", line 496, in <module>\n    raise 404\n'
2024-12-16T23:05:57 exceptions must derive from BaseException
2024-12-16T23:05:57 '  File "poe_2_lost_city.py", line 496, in <module>\n    raise 404\n'
2024-12-16T23:06:18 exceptions must derive from BaseException
2024-12-16T23:06:18 '  File "poe_2_lost_city.py", line 496, in <module>\n    raise 404\n'
2024-12-16T23:06:39 exceptions must derive from BaseException
2024-12-16T23:06:39 '  File "poe_2_lost_city.py", line 496, in <module>\n    raise 404\n'
2024-12-16T23:06:58 exceptions must derive from BaseException
2024-12-16T23:06:58 '  File "poe_2_lost_city.py", line 496, in <module>\n    raise 404\n'
2024-12-16T23:07:19 exceptions must derive from BaseException
2024-12-16T23:07:19 '  File "poe_2_lost_city.py", line 496, in <module>\n    raise 404\n'
2024-12-16T23:07:40 exceptions must derive from BaseException
2024-12-16T23:07:40 '  File "poe_2_lost_city.py", line 496, in <module>\n    raise 404\n'
2024-12-16T23:08:00 exceptions must derive from BaseException
2024-12-16T23:08:00 '  File "poe_2_lost_city.py", line 496, in <module>\n    raise 404\n'
2024-12-16T23:08:17 exceptions must derive from BaseException
2024-12-16T23:08:17 '  File "poe_2_lost_city.py", line 496, in <module>\n    raise 404\n'
2024-12-16T23:08:29 exceptions must derive from BaseException
2024-12-16T23:08:29 '  File "poe_2_lost_city.py", line 496, in <module>\n    raise 404\n'
2024-12-16T23:08:42 exceptions must derive from BaseException
2024-12-16T23:08:42 '  File "poe_2_lost_city.py", line 496, in <module>\n    raise 404\n'
2024-12-16T23:08:56 exceptions must derive from BaseException
2024-12-16T23:08:56 '  File "poe_2_lost_city.py", line 496, in <module>\n    raise 404\n'
2024-12-16T23:09:10 exceptions must derive from BaseException
2024-12-16T23:09:10 '  File "poe_2_lost_city.py", line 496, in <module>\n    raise 404\n'
