2024-09-28T15:32:17 1_2_5_2 current area isn't supported
2024-09-28T15:32:17 1_2_5_2 current area isn't supported
2024-09-28T15:32:17 '  File "quest.py", line 4553, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T15:32:17 '  File "quest.py", line 4543, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T15:33:24 1_2_5_2 current area isn't supported
2024-09-28T15:33:24 1_2_5_2 current area isn't supported
2024-09-28T15:33:24 '  File "quest.py", line 4553, in <module>\n    poe_bot.refreshInstanceData()\n'
2024-09-28T15:33:24 '  File "quest.py", line 4543, in getQuestArea\n    if area_class is None:\n'
2024-09-28T15:36:04 exceptions must derive from BaseException
2024-09-28T15:36:04 exceptions must derive from BaseException
2024-09-28T15:36:04 '  File "quest.py", line 4555, in <module>\n    current_quest_area.complete()\n'
2024-09-28T15:36:04 '  File "quest.py", line 1191, in complete\n    raise "completed"\n'
2024-09-28T15:55:03 exceptions must derive from BaseException
2024-09-28T15:55:03 exceptions must derive from BaseException
2024-09-28T15:55:03 '  File "quest.py", line 4529, in <module>\n    current_quest_area.complete()\n'
2024-09-28T15:55:03 '  File "quest.py", line 1191, in complete\n    raise "completed"\n'
2024-09-28T16:03:23 exceptions must derive from BaseException
2024-09-28T16:03:23 exceptions must derive from BaseException
2024-09-28T16:03:23 '  File "quest.py", line 4529, in <module>\n    current_quest_area.complete()\n'
2024-09-28T16:03:23 '  File "quest.py", line 1191, in complete\n    raise "completed"\n'
2024-09-28T16:07:01 exceptions must derive from BaseException
2024-09-28T16:07:01 exceptions must derive from BaseException
2024-09-28T16:07:01 '  File "quest.py", line 4529, in <module>\n    current_quest_area.complete()\n'
2024-09-28T16:07:01 '  File "quest.py", line 1191, in complete\n    raise "completed"\n'
2024-09-28T16:09:33 exceptions must derive from BaseException
2024-09-28T16:09:33 exceptions must derive from BaseException
2024-09-28T16:09:33 '  File "quest.py", line 4529, in <module>\n    current_quest_area.complete()\n'
2024-09-28T16:09:33 '  File "quest.py", line 1191, in complete\n    raise "completed"\n'
2024-09-28T16:20:25 exceptions must derive from BaseException
2024-09-28T16:20:25 exceptions must derive from BaseException
2024-09-28T16:20:25 '  File "quest.py", line 4529, in <module>\n    current_quest_area.complete()\n'
2024-09-28T16:20:25 '  File "quest.py", line 1191, in complete\n    raise "completed"\n'
2024-09-28T16:21:27 exceptions must derive from BaseException
2024-09-28T16:21:27 exceptions must derive from BaseException
2024-09-28T16:21:27 '  File "quest.py", line 4529, in <module>\n    current_quest_area.complete()\n'
2024-09-28T16:21:27 '  File "quest.py", line 1191, in complete\n    raise "completed"\n'
2024-09-28T16:22:44 exceptions must derive from BaseException
2024-09-28T16:22:44 exceptions must derive from BaseException
2024-09-28T16:22:44 '  File "quest.py", line 4529, in <module>\n    current_quest_area.complete()\n'
2024-09-28T16:22:44 '  File "quest.py", line 1191, in complete\n    raise "completed"\n'
2024-09-28T16:23:45 exceptions must derive from BaseException
2024-09-28T16:23:45 exceptions must derive from BaseException
2024-09-28T16:23:45 '  File "quest.py", line 4529, in <module>\n    current_quest_area.complete()\n'
2024-09-28T16:23:45 '  File "quest.py", line 1191, in complete\n    raise "completed"\n'
2024-09-28T16:24:42 exceptions must derive from BaseException
2024-09-28T16:24:42 exceptions must derive from BaseException
2024-09-28T16:24:42 '  File "quest.py", line 4529, in <module>\n    current_quest_area.complete()\n'
2024-09-28T16:24:42 '  File "quest.py", line 1191, in complete\n    raise "completed"\n'
2024-09-28T16:25:43 exceptions must derive from BaseException
2024-09-28T16:25:43 exceptions must derive from BaseException
2024-09-28T16:25:43 '  File "quest.py", line 4529, in <module>\n    current_quest_area.complete()\n'
2024-09-28T16:25:43 '  File "quest.py", line 1191, in complete\n    raise "completed"\n'
2024-09-28T16:26:40 exceptions must derive from BaseException
2024-09-28T16:26:40 exceptions must derive from BaseException
2024-09-28T16:26:40 '  File "quest.py", line 4529, in <module>\n    current_quest_area.complete()\n'
2024-09-28T16:26:40 '  File "quest.py", line 1191, in complete\n    raise "completed"\n'
2024-09-28T16:27:35 exceptions must derive from BaseException
2024-09-28T16:27:35 exceptions must derive from BaseException
2024-09-28T16:27:35 '  File "quest.py", line 4529, in <module>\n    current_quest_area.complete()\n'
2024-09-28T16:27:35 '  File "quest.py", line 1191, in complete\n    raise "completed"\n'
2024-09-28T16:28:43 exceptions must derive from BaseException
2024-09-28T16:28:43 exceptions must derive from BaseException
2024-09-28T16:28:43 '  File "quest.py", line 4529, in <module>\n    current_quest_area.complete()\n'
2024-09-28T16:28:43 '  File "quest.py", line 1191, in complete\n    raise "completed"\n'
2024-09-28T16:29:40 exceptions must derive from BaseException
2024-09-28T16:29:40 exceptions must derive from BaseException
2024-09-28T16:29:40 '  File "quest.py", line 4529, in <module>\n    current_quest_area.complete()\n'
2024-09-28T16:29:40 '  File "quest.py", line 1191, in complete\n    raise "completed"\n'
2024-09-28T16:30:35 exceptions must derive from BaseException
2024-09-28T16:30:35 exceptions must derive from BaseException
2024-09-28T16:30:35 '  File "quest.py", line 4529, in <module>\n    current_quest_area.complete()\n'
2024-09-28T16:30:35 '  File "quest.py", line 1191, in complete\n    raise "completed"\n'
2024-09-28T16:31:44 exceptions must derive from BaseException
2024-09-28T16:31:44 exceptions must derive from BaseException
2024-09-28T16:31:44 '  File "quest.py", line 4529, in <module>\n    current_quest_area.complete()\n'
2024-09-28T16:31:44 '  File "quest.py", line 1191, in complete\n    raise "completed"\n'
2024-09-28T16:33:10 exceptions must derive from BaseException
2024-09-28T16:33:10 exceptions must derive from BaseException
2024-09-28T16:33:10 '  File "quest.py", line 4529, in <module>\n    current_quest_area.complete()\n'
2024-09-28T16:33:10 '  File "quest.py", line 1191, in complete\n    raise "completed"\n'
2024-09-28T16:34:27 exceptions must derive from BaseException
2024-09-28T16:34:27 exceptions must derive from BaseException
2024-09-28T16:34:27 '  File "quest.py", line 4529, in <module>\n    current_quest_area.complete()\n'
2024-09-28T16:34:27 '  File "quest.py", line 1191, in complete\n    raise "completed"\n'
2024-09-28T16:35:24 exceptions must derive from BaseException
2024-09-28T16:35:24 exceptions must derive from BaseException
2024-09-28T16:35:24 '  File "quest.py", line 4529, in <module>\n    current_quest_area.complete()\n'
2024-09-28T16:35:24 '  File "quest.py", line 1191, in complete\n    raise "completed"\n'
2024-09-28T16:36:20 exceptions must derive from BaseException
2024-09-28T16:36:20 exceptions must derive from BaseException
2024-09-28T16:36:20 '  File "quest.py", line 4529, in <module>\n    current_quest_area.complete()\n'
2024-09-28T16:36:20 '  File "quest.py", line 1191, in complete\n    raise "completed"\n'
2024-09-28T16:37:16 exceptions must derive from BaseException
2024-09-28T16:37:16 exceptions must derive from BaseException
2024-09-28T16:37:16 '  File "quest.py", line 4529, in <module>\n    current_quest_area.complete()\n'
2024-09-28T16:37:16 '  File "quest.py", line 1191, in complete\n    raise "completed"\n'
2024-09-28T16:38:23 exceptions must derive from BaseException
2024-09-28T16:38:23 exceptions must derive from BaseException
2024-09-28T16:38:23 '  File "quest.py", line 4529, in <module>\n    current_quest_area.complete()\n'
2024-09-28T16:38:23 '  File "quest.py", line 1191, in complete\n    raise "completed"\n'
2024-09-28T16:39:19 exceptions must derive from BaseException
2024-09-28T16:39:19 exceptions must derive from BaseException
2024-09-28T16:39:19 '  File "quest.py", line 4529, in <module>\n    current_quest_area.complete()\n'
2024-09-28T16:39:19 '  File "quest.py", line 1191, in complete\n    raise "completed"\n'
2024-09-28T16:40:14 exceptions must derive from BaseException
2024-09-28T16:40:14 exceptions must derive from BaseException
2024-09-28T16:40:14 '  File "quest.py", line 4529, in <module>\n    current_quest_area.complete()\n'
2024-09-28T16:40:14 '  File "quest.py", line 1191, in complete\n    raise "completed"\n'
2024-09-28T16:41:22 exceptions must derive from BaseException
2024-09-28T16:41:22 exceptions must derive from BaseException
2024-09-28T16:41:22 '  File "quest.py", line 4529, in <module>\n    current_quest_area.complete()\n'
2024-09-28T16:41:22 '  File "quest.py", line 1191, in complete\n    raise "completed"\n'
2024-09-28T16:42:24 exceptions must derive from BaseException
2024-09-28T16:42:24 exceptions must derive from BaseException
2024-09-28T16:42:24 '  File "quest.py", line 4529, in <module>\n    current_quest_area.complete()\n'
2024-09-28T16:42:24 '  File "quest.py", line 1191, in complete\n    raise "completed"\n'
2024-09-28T16:54:29 list index out of range
2024-09-28T16:54:29 list index out of range
2024-09-28T16:54:29 '  File "quest.py", line 748, in <module>\n    poe_bot.game_data.terrain.getCurrentlyPassableArea()\n'
2024-09-28T16:54:29 '  File "C:\\poe_bot\\1_host\\utils\\gamehelper.py", line 506, in getCurrentlyPassableArea\n    nearest_passable_player_point = list(list(zip(nearest_passable_player_points[0], nearest_passable_player_points[1]))[0])\n'
2024-09-28T16:58:09 relogging
2024-09-28T17:00:44 1_2_town current area isn't supported
2024-09-28T17:00:44 1_2_town current area isn't supported
2024-09-28T17:00:44 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:00:44 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:00:46 1_2_town current area isn't supported
2024-09-28T17:00:46 1_2_town current area isn't supported
2024-09-28T17:00:46 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:00:46 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:00:49 1_2_town current area isn't supported
2024-09-28T17:00:49 1_2_town current area isn't supported
2024-09-28T17:00:49 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:00:49 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:00:51 1_2_town current area isn't supported
2024-09-28T17:00:51 1_2_town current area isn't supported
2024-09-28T17:00:51 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:00:51 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:00:53 1_2_town current area isn't supported
2024-09-28T17:00:53 1_2_town current area isn't supported
2024-09-28T17:00:53 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:00:53 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:00:55 1_2_town current area isn't supported
2024-09-28T17:00:55 1_2_town current area isn't supported
2024-09-28T17:00:55 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:00:55 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:00:57 1_2_town current area isn't supported
2024-09-28T17:00:57 1_2_town current area isn't supported
2024-09-28T17:00:57 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:00:57 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:00:59 1_2_town current area isn't supported
2024-09-28T17:00:59 1_2_town current area isn't supported
2024-09-28T17:00:59 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:00:59 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:01:01 1_2_town current area isn't supported
2024-09-28T17:01:01 1_2_town current area isn't supported
2024-09-28T17:01:01 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:01:01 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:01:03 1_2_town current area isn't supported
2024-09-28T17:01:03 1_2_town current area isn't supported
2024-09-28T17:01:03 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:01:03 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:01:05 1_2_town current area isn't supported
2024-09-28T17:01:05 1_2_town current area isn't supported
2024-09-28T17:01:05 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:01:05 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:01:07 1_2_town current area isn't supported
2024-09-28T17:01:07 1_2_town current area isn't supported
2024-09-28T17:01:07 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:01:07 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:01:09 1_2_town current area isn't supported
2024-09-28T17:01:09 1_2_town current area isn't supported
2024-09-28T17:01:09 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:01:09 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:01:11 1_2_town current area isn't supported
2024-09-28T17:01:11 1_2_town current area isn't supported
2024-09-28T17:01:11 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:01:11 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:01:13 1_2_town current area isn't supported
2024-09-28T17:01:13 1_2_town current area isn't supported
2024-09-28T17:01:13 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:01:13 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:01:15 1_2_town current area isn't supported
2024-09-28T17:01:15 1_2_town current area isn't supported
2024-09-28T17:01:15 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:01:15 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:01:18 1_2_town current area isn't supported
2024-09-28T17:01:18 1_2_town current area isn't supported
2024-09-28T17:01:18 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:01:18 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:01:20 1_2_town current area isn't supported
2024-09-28T17:01:20 1_2_town current area isn't supported
2024-09-28T17:01:20 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:01:20 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:01:22 1_2_town current area isn't supported
2024-09-28T17:01:22 1_2_town current area isn't supported
2024-09-28T17:01:22 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:01:22 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:01:24 1_2_town current area isn't supported
2024-09-28T17:01:24 1_2_town current area isn't supported
2024-09-28T17:01:24 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:01:24 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:01:26 1_2_town current area isn't supported
2024-09-28T17:01:26 1_2_town current area isn't supported
2024-09-28T17:01:26 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:01:26 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:01:28 1_2_town current area isn't supported
2024-09-28T17:01:28 1_2_town current area isn't supported
2024-09-28T17:01:28 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:01:28 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:01:30 1_2_town current area isn't supported
2024-09-28T17:01:30 1_2_town current area isn't supported
2024-09-28T17:01:30 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:01:30 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:01:32 1_2_town current area isn't supported
2024-09-28T17:01:32 1_2_town current area isn't supported
2024-09-28T17:01:32 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:01:32 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:01:35 1_2_town current area isn't supported
2024-09-28T17:01:35 1_2_town current area isn't supported
2024-09-28T17:01:35 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:01:35 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:01:37 1_2_town current area isn't supported
2024-09-28T17:01:37 1_2_town current area isn't supported
2024-09-28T17:01:37 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:01:37 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:01:38 1_2_town current area isn't supported
2024-09-28T17:01:38 1_2_town current area isn't supported
2024-09-28T17:01:38 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:01:38 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:01:41 1_2_town current area isn't supported
2024-09-28T17:01:41 1_2_town current area isn't supported
2024-09-28T17:01:41 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:01:41 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:01:43 1_2_town current area isn't supported
2024-09-28T17:01:43 1_2_town current area isn't supported
2024-09-28T17:01:43 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:01:43 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:01:45 1_2_town current area isn't supported
2024-09-28T17:01:45 1_2_town current area isn't supported
2024-09-28T17:01:45 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:01:45 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:01:47 1_2_town current area isn't supported
2024-09-28T17:01:47 1_2_town current area isn't supported
2024-09-28T17:01:47 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:01:47 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:01:49 1_2_town current area isn't supported
2024-09-28T17:01:49 1_2_town current area isn't supported
2024-09-28T17:01:49 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:01:49 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:01:51 1_2_town current area isn't supported
2024-09-28T17:01:51 1_2_town current area isn't supported
2024-09-28T17:01:51 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:01:51 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:01:53 1_2_town current area isn't supported
2024-09-28T17:01:53 1_2_town current area isn't supported
2024-09-28T17:01:53 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:01:53 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:01:55 1_2_town current area isn't supported
2024-09-28T17:01:55 1_2_town current area isn't supported
2024-09-28T17:01:55 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:01:55 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:01:57 1_2_town current area isn't supported
2024-09-28T17:01:57 1_2_town current area isn't supported
2024-09-28T17:01:57 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:01:57 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:01:59 1_2_town current area isn't supported
2024-09-28T17:01:59 1_2_town current area isn't supported
2024-09-28T17:01:59 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:01:59 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:02:01 1_2_town current area isn't supported
2024-09-28T17:02:01 1_2_town current area isn't supported
2024-09-28T17:02:01 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:02:01 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:02:03 1_2_town current area isn't supported
2024-09-28T17:02:03 1_2_town current area isn't supported
2024-09-28T17:02:03 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:02:03 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:02:03 1_2_town current area isn't supported
2024-09-28T17:02:03 1_2_town current area isn't supported
2024-09-28T17:02:03 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:02:03 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:02:06 1_2_town current area isn't supported
2024-09-28T17:02:06 1_2_town current area isn't supported
2024-09-28T17:02:06 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:02:06 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:02:08 1_2_town current area isn't supported
2024-09-28T17:02:08 1_2_town current area isn't supported
2024-09-28T17:02:08 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:02:08 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:02:10 1_2_town current area isn't supported
2024-09-28T17:02:10 1_2_town current area isn't supported
2024-09-28T17:02:10 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:02:10 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:02:12 1_2_town current area isn't supported
2024-09-28T17:02:12 1_2_town current area isn't supported
2024-09-28T17:02:12 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:02:12 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:02:14 1_2_town current area isn't supported
2024-09-28T17:02:14 1_2_town current area isn't supported
2024-09-28T17:02:14 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:02:14 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:02:16 1_2_town current area isn't supported
2024-09-28T17:02:16 1_2_town current area isn't supported
2024-09-28T17:02:16 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:02:16 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:02:18 1_2_town current area isn't supported
2024-09-28T17:02:18 1_2_town current area isn't supported
2024-09-28T17:02:18 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:02:18 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:02:20 1_2_town current area isn't supported
2024-09-28T17:02:20 1_2_town current area isn't supported
2024-09-28T17:02:20 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:02:20 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:02:22 1_2_town current area isn't supported
2024-09-28T17:02:22 1_2_town current area isn't supported
2024-09-28T17:02:22 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:02:22 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:02:24 1_2_town current area isn't supported
2024-09-28T17:02:24 1_2_town current area isn't supported
2024-09-28T17:02:24 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:02:24 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:02:26 1_2_town current area isn't supported
2024-09-28T17:02:26 1_2_town current area isn't supported
2024-09-28T17:02:26 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:02:26 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:02:28 1_2_town current area isn't supported
2024-09-28T17:02:28 1_2_town current area isn't supported
2024-09-28T17:02:28 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:02:28 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:02:30 1_2_town current area isn't supported
2024-09-28T17:02:30 1_2_town current area isn't supported
2024-09-28T17:02:30 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:02:30 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:02:32 1_2_town current area isn't supported
2024-09-28T17:02:32 1_2_town current area isn't supported
2024-09-28T17:02:32 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:02:32 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:02:34 1_2_town current area isn't supported
2024-09-28T17:02:34 1_2_town current area isn't supported
2024-09-28T17:02:34 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:02:34 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:02:36 1_2_town current area isn't supported
2024-09-28T17:02:36 1_2_town current area isn't supported
2024-09-28T17:02:36 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:02:36 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:02:38 1_2_town current area isn't supported
2024-09-28T17:02:38 1_2_town current area isn't supported
2024-09-28T17:02:38 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:02:38 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:02:40 1_2_town current area isn't supported
2024-09-28T17:02:40 1_2_town current area isn't supported
2024-09-28T17:02:40 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:02:40 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:02:42 1_2_town current area isn't supported
2024-09-28T17:02:42 1_2_town current area isn't supported
2024-09-28T17:02:42 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:02:42 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:02:44 1_2_town current area isn't supported
2024-09-28T17:02:44 1_2_town current area isn't supported
2024-09-28T17:02:44 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:02:44 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:02:46 1_2_town current area isn't supported
2024-09-28T17:02:46 1_2_town current area isn't supported
2024-09-28T17:02:46 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:02:46 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:02:48 1_2_town current area isn't supported
2024-09-28T17:02:48 1_2_town current area isn't supported
2024-09-28T17:02:48 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:02:48 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:02:51 1_2_town current area isn't supported
2024-09-28T17:02:51 1_2_town current area isn't supported
2024-09-28T17:02:51 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:02:51 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:02:53 1_2_town current area isn't supported
2024-09-28T17:02:53 1_2_town current area isn't supported
2024-09-28T17:02:53 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:02:53 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:02:55 1_2_town current area isn't supported
2024-09-28T17:02:55 1_2_town current area isn't supported
2024-09-28T17:02:55 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:02:55 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:02:57 1_2_town current area isn't supported
2024-09-28T17:02:57 1_2_town current area isn't supported
2024-09-28T17:02:57 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:02:57 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:02:59 1_2_town current area isn't supported
2024-09-28T17:02:59 1_2_town current area isn't supported
2024-09-28T17:02:59 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:02:59 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:03:01 1_2_town current area isn't supported
2024-09-28T17:03:01 1_2_town current area isn't supported
2024-09-28T17:03:01 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:03:01 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:03:03 1_2_town current area isn't supported
2024-09-28T17:03:03 1_2_town current area isn't supported
2024-09-28T17:03:03 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:03:03 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:03:05 1_2_town current area isn't supported
2024-09-28T17:03:05 1_2_town current area isn't supported
2024-09-28T17:03:05 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:03:05 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:03:07 1_2_town current area isn't supported
2024-09-28T17:03:07 1_2_town current area isn't supported
2024-09-28T17:03:07 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:03:07 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:03:09 1_2_town current area isn't supported
2024-09-28T17:03:09 1_2_town current area isn't supported
2024-09-28T17:03:09 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:03:09 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:03:11 1_2_town current area isn't supported
2024-09-28T17:03:11 1_2_town current area isn't supported
2024-09-28T17:03:11 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:03:11 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:03:13 1_2_town current area isn't supported
2024-09-28T17:03:13 1_2_town current area isn't supported
2024-09-28T17:03:13 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:03:13 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:03:15 1_2_town current area isn't supported
2024-09-28T17:03:15 1_2_town current area isn't supported
2024-09-28T17:03:15 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:03:15 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:03:17 1_2_town current area isn't supported
2024-09-28T17:03:17 1_2_town current area isn't supported
2024-09-28T17:03:17 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:03:17 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:03:19 1_2_town current area isn't supported
2024-09-28T17:03:19 1_2_town current area isn't supported
2024-09-28T17:03:19 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:03:19 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:03:21 1_2_town current area isn't supported
2024-09-28T17:03:21 1_2_town current area isn't supported
2024-09-28T17:03:21 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:03:21 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:03:23 1_2_town current area isn't supported
2024-09-28T17:03:23 1_2_town current area isn't supported
2024-09-28T17:03:23 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:03:23 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:03:26 1_2_town current area isn't supported
2024-09-28T17:03:26 1_2_town current area isn't supported
2024-09-28T17:03:26 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:03:26 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:03:28 1_2_town current area isn't supported
2024-09-28T17:03:28 1_2_town current area isn't supported
2024-09-28T17:03:28 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:03:28 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:03:30 1_2_town current area isn't supported
2024-09-28T17:03:30 1_2_town current area isn't supported
2024-09-28T17:03:30 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:03:30 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:03:33 1_2_town current area isn't supported
2024-09-28T17:03:33 1_2_town current area isn't supported
2024-09-28T17:03:33 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:03:33 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:03:35 1_2_town current area isn't supported
2024-09-28T17:03:35 1_2_town current area isn't supported
2024-09-28T17:03:35 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:03:35 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:03:37 1_2_town current area isn't supported
2024-09-28T17:03:37 1_2_town current area isn't supported
2024-09-28T17:03:37 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:03:37 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:03:40 1_2_town current area isn't supported
2024-09-28T17:03:40 1_2_town current area isn't supported
2024-09-28T17:03:40 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:03:40 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:03:42 1_2_town current area isn't supported
2024-09-28T17:03:42 1_2_town current area isn't supported
2024-09-28T17:03:42 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:03:42 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:03:44 1_2_town current area isn't supported
2024-09-28T17:03:44 1_2_town current area isn't supported
2024-09-28T17:03:44 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:03:44 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:03:47 1_2_town current area isn't supported
2024-09-28T17:03:47 1_2_town current area isn't supported
2024-09-28T17:03:47 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:03:47 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:03:49 1_2_town current area isn't supported
2024-09-28T17:03:49 1_2_town current area isn't supported
2024-09-28T17:03:49 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:03:49 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:03:51 1_2_town current area isn't supported
2024-09-28T17:03:51 1_2_town current area isn't supported
2024-09-28T17:03:51 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:03:51 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:03:53 1_2_town current area isn't supported
2024-09-28T17:03:53 1_2_town current area isn't supported
2024-09-28T17:03:53 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:03:53 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:03:56 1_2_town current area isn't supported
2024-09-28T17:03:56 1_2_town current area isn't supported
2024-09-28T17:03:56 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:03:56 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:03:58 1_2_town current area isn't supported
2024-09-28T17:03:58 1_2_town current area isn't supported
2024-09-28T17:03:58 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:03:58 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:04:00 1_2_town current area isn't supported
2024-09-28T17:04:00 1_2_town current area isn't supported
2024-09-28T17:04:00 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:04:00 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:04:02 1_2_town current area isn't supported
2024-09-28T17:04:02 1_2_town current area isn't supported
2024-09-28T17:04:02 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:04:02 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:04:04 1_2_town current area isn't supported
2024-09-28T17:04:04 1_2_town current area isn't supported
2024-09-28T17:04:04 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:04:04 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:04:06 1_2_town current area isn't supported
2024-09-28T17:04:06 1_2_town current area isn't supported
2024-09-28T17:04:06 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:04:06 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:04:08 1_2_town current area isn't supported
2024-09-28T17:04:08 1_2_town current area isn't supported
2024-09-28T17:04:08 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:04:08 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:04:11 1_2_town current area isn't supported
2024-09-28T17:04:11 1_2_town current area isn't supported
2024-09-28T17:04:11 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:04:11 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:04:13 1_2_town current area isn't supported
2024-09-28T17:04:13 1_2_town current area isn't supported
2024-09-28T17:04:13 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:04:13 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:04:15 1_2_town current area isn't supported
2024-09-28T17:04:15 1_2_town current area isn't supported
2024-09-28T17:04:15 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:04:15 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:04:17 1_2_town current area isn't supported
2024-09-28T17:04:17 1_2_town current area isn't supported
2024-09-28T17:04:17 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:04:17 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:04:19 1_2_town current area isn't supported
2024-09-28T17:04:19 1_2_town current area isn't supported
2024-09-28T17:04:19 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:04:19 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:04:21 1_2_town current area isn't supported
2024-09-28T17:04:21 1_2_town current area isn't supported
2024-09-28T17:04:21 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:04:21 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:04:23 1_2_town current area isn't supported
2024-09-28T17:04:23 1_2_town current area isn't supported
2024-09-28T17:04:23 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:04:23 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:04:26 1_2_town current area isn't supported
2024-09-28T17:04:26 1_2_town current area isn't supported
2024-09-28T17:04:26 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:04:26 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:04:28 1_2_town current area isn't supported
2024-09-28T17:04:28 1_2_town current area isn't supported
2024-09-28T17:04:28 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:04:28 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:04:30 1_2_town current area isn't supported
2024-09-28T17:04:30 1_2_town current area isn't supported
2024-09-28T17:04:30 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:04:30 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:04:32 1_2_town current area isn't supported
2024-09-28T17:04:32 1_2_town current area isn't supported
2024-09-28T17:04:32 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:04:32 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:04:34 1_2_town current area isn't supported
2024-09-28T17:04:34 1_2_town current area isn't supported
2024-09-28T17:04:34 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:04:34 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:04:36 1_2_town current area isn't supported
2024-09-28T17:04:36 1_2_town current area isn't supported
2024-09-28T17:04:36 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:04:36 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:04:38 1_2_town current area isn't supported
2024-09-28T17:04:38 1_2_town current area isn't supported
2024-09-28T17:04:38 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:04:38 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:04:45 1_2_town current area isn't supported
2024-09-28T17:04:45 1_2_town current area isn't supported
2024-09-28T17:04:45 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:04:45 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:04:47 1_2_town current area isn't supported
2024-09-28T17:04:47 1_2_town current area isn't supported
2024-09-28T17:04:47 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:04:47 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:04:49 1_2_town current area isn't supported
2024-09-28T17:04:49 1_2_town current area isn't supported
2024-09-28T17:04:49 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:04:49 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:04:51 1_2_town current area isn't supported
2024-09-28T17:04:51 1_2_town current area isn't supported
2024-09-28T17:04:51 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:04:51 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:04:54 1_2_town current area isn't supported
2024-09-28T17:04:54 1_2_town current area isn't supported
2024-09-28T17:04:54 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:04:54 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:04:56 1_2_town current area isn't supported
2024-09-28T17:04:56 1_2_town current area isn't supported
2024-09-28T17:04:56 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:04:56 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:04:58 1_2_town current area isn't supported
2024-09-28T17:04:58 1_2_town current area isn't supported
2024-09-28T17:04:58 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:04:58 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:05:00 1_2_town current area isn't supported
2024-09-28T17:05:00 1_2_town current area isn't supported
2024-09-28T17:05:00 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:05:00 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:05:02 1_2_town current area isn't supported
2024-09-28T17:05:02 1_2_town current area isn't supported
2024-09-28T17:05:02 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:05:02 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:05:04 1_2_town current area isn't supported
2024-09-28T17:05:04 1_2_town current area isn't supported
2024-09-28T17:05:04 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:05:04 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:05:06 1_2_town current area isn't supported
2024-09-28T17:05:06 1_2_town current area isn't supported
2024-09-28T17:05:06 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:05:06 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:05:08 1_2_town current area isn't supported
2024-09-28T17:05:08 1_2_town current area isn't supported
2024-09-28T17:05:08 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:05:08 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:05:10 1_2_town current area isn't supported
2024-09-28T17:05:10 1_2_town current area isn't supported
2024-09-28T17:05:10 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:05:10 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:05:12 1_2_town current area isn't supported
2024-09-28T17:05:12 1_2_town current area isn't supported
2024-09-28T17:05:12 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:05:12 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:05:14 1_2_town current area isn't supported
2024-09-28T17:05:14 1_2_town current area isn't supported
2024-09-28T17:05:14 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:05:14 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:05:16 1_2_town current area isn't supported
2024-09-28T17:05:16 1_2_town current area isn't supported
2024-09-28T17:05:16 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:05:16 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:05:18 1_2_town current area isn't supported
2024-09-28T17:05:18 1_2_town current area isn't supported
2024-09-28T17:05:18 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:05:18 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:05:20 1_2_town current area isn't supported
2024-09-28T17:05:20 1_2_town current area isn't supported
2024-09-28T17:05:20 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:05:20 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:05:22 1_2_town current area isn't supported
2024-09-28T17:05:22 1_2_town current area isn't supported
2024-09-28T17:05:22 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:05:22 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:05:24 1_2_town current area isn't supported
2024-09-28T17:05:24 1_2_town current area isn't supported
2024-09-28T17:05:24 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:05:24 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:05:26 1_2_town current area isn't supported
2024-09-28T17:05:26 1_2_town current area isn't supported
2024-09-28T17:05:26 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:05:26 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:05:28 1_2_town current area isn't supported
2024-09-28T17:05:28 1_2_town current area isn't supported
2024-09-28T17:05:28 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:05:28 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:05:30 1_2_town current area isn't supported
2024-09-28T17:05:30 1_2_town current area isn't supported
2024-09-28T17:05:30 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:05:30 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:05:32 1_2_town current area isn't supported
2024-09-28T17:05:32 1_2_town current area isn't supported
2024-09-28T17:05:32 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:05:32 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:05:34 1_2_town current area isn't supported
2024-09-28T17:05:34 1_2_town current area isn't supported
2024-09-28T17:05:34 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:05:34 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:05:36 1_2_town current area isn't supported
2024-09-28T17:05:36 1_2_town current area isn't supported
2024-09-28T17:05:36 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:05:36 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:05:38 1_2_town current area isn't supported
2024-09-28T17:05:38 1_2_town current area isn't supported
2024-09-28T17:05:38 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:05:38 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:05:40 1_2_town current area isn't supported
2024-09-28T17:05:40 1_2_town current area isn't supported
2024-09-28T17:05:40 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:05:40 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:05:42 1_2_town current area isn't supported
2024-09-28T17:05:42 1_2_town current area isn't supported
2024-09-28T17:05:42 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:05:42 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:05:44 1_2_town current area isn't supported
2024-09-28T17:05:44 1_2_town current area isn't supported
2024-09-28T17:05:44 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:05:44 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:05:46 1_2_town current area isn't supported
2024-09-28T17:05:46 1_2_town current area isn't supported
2024-09-28T17:05:46 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:05:46 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:05:48 1_2_town current area isn't supported
2024-09-28T17:05:48 1_2_town current area isn't supported
2024-09-28T17:05:48 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:05:48 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:05:50 1_2_town current area isn't supported
2024-09-28T17:05:50 1_2_town current area isn't supported
2024-09-28T17:05:50 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:05:50 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:05:52 1_2_town current area isn't supported
2024-09-28T17:05:52 1_2_town current area isn't supported
2024-09-28T17:05:52 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:05:52 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:05:54 1_2_town current area isn't supported
2024-09-28T17:05:54 1_2_town current area isn't supported
2024-09-28T17:05:54 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:05:54 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:05:56 1_2_town current area isn't supported
2024-09-28T17:05:56 1_2_town current area isn't supported
2024-09-28T17:05:56 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:05:56 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:05:58 1_2_town current area isn't supported
2024-09-28T17:05:58 1_2_town current area isn't supported
2024-09-28T17:05:58 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:05:58 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:06:00 1_2_town current area isn't supported
2024-09-28T17:06:00 1_2_town current area isn't supported
2024-09-28T17:06:00 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:06:00 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:06:02 1_2_town current area isn't supported
2024-09-28T17:06:02 1_2_town current area isn't supported
2024-09-28T17:06:02 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:06:02 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:06:05 1_2_town current area isn't supported
2024-09-28T17:06:05 1_2_town current area isn't supported
2024-09-28T17:06:05 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:06:05 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:06:07 1_2_town current area isn't supported
2024-09-28T17:06:07 1_2_town current area isn't supported
2024-09-28T17:06:07 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:06:07 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:06:09 1_2_town current area isn't supported
2024-09-28T17:06:09 1_2_town current area isn't supported
2024-09-28T17:06:09 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:06:09 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:06:12 1_2_town current area isn't supported
2024-09-28T17:06:12 1_2_town current area isn't supported
2024-09-28T17:06:12 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:06:12 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:06:15 1_2_town current area isn't supported
2024-09-28T17:06:15 1_2_town current area isn't supported
2024-09-28T17:06:15 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:06:15 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:06:17 1_2_town current area isn't supported
2024-09-28T17:06:17 1_2_town current area isn't supported
2024-09-28T17:06:17 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:06:17 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:06:19 1_2_town current area isn't supported
2024-09-28T17:06:19 1_2_town current area isn't supported
2024-09-28T17:06:19 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:06:19 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:06:22 1_2_town current area isn't supported
2024-09-28T17:06:22 1_2_town current area isn't supported
2024-09-28T17:06:22 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:06:22 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:06:24 1_2_town current area isn't supported
2024-09-28T17:06:24 1_2_town current area isn't supported
2024-09-28T17:06:24 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:06:24 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:06:26 1_2_town current area isn't supported
2024-09-28T17:06:26 1_2_town current area isn't supported
2024-09-28T17:06:26 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:06:26 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:06:28 1_2_town current area isn't supported
2024-09-28T17:06:28 1_2_town current area isn't supported
2024-09-28T17:06:28 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:06:28 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:06:30 1_2_town current area isn't supported
2024-09-28T17:06:30 1_2_town current area isn't supported
2024-09-28T17:06:30 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:06:30 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:06:32 1_2_town current area isn't supported
2024-09-28T17:06:32 1_2_town current area isn't supported
2024-09-28T17:06:32 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:06:32 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:06:34 1_2_town current area isn't supported
2024-09-28T17:06:34 1_2_town current area isn't supported
2024-09-28T17:06:34 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:06:34 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:06:36 1_2_town current area isn't supported
2024-09-28T17:06:36 1_2_town current area isn't supported
2024-09-28T17:06:36 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:06:36 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:06:38 1_2_town current area isn't supported
2024-09-28T17:06:38 1_2_town current area isn't supported
2024-09-28T17:06:38 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:06:38 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:06:40 1_2_town current area isn't supported
2024-09-28T17:06:40 1_2_town current area isn't supported
2024-09-28T17:06:40 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:06:40 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:06:42 1_2_town current area isn't supported
2024-09-28T17:06:42 1_2_town current area isn't supported
2024-09-28T17:06:42 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:06:42 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:06:44 1_2_town current area isn't supported
2024-09-28T17:06:44 1_2_town current area isn't supported
2024-09-28T17:06:44 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:06:44 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:06:46 1_2_town current area isn't supported
2024-09-28T17:06:46 1_2_town current area isn't supported
2024-09-28T17:06:46 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:06:46 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:06:48 1_2_town current area isn't supported
2024-09-28T17:06:48 1_2_town current area isn't supported
2024-09-28T17:06:48 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:06:48 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:06:50 1_2_town current area isn't supported
2024-09-28T17:06:50 1_2_town current area isn't supported
2024-09-28T17:06:50 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:06:50 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:06:52 1_2_town current area isn't supported
2024-09-28T17:06:52 1_2_town current area isn't supported
2024-09-28T17:06:52 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:06:52 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:06:54 1_2_town current area isn't supported
2024-09-28T17:06:54 1_2_town current area isn't supported
2024-09-28T17:06:54 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:06:54 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:06:56 1_2_town current area isn't supported
2024-09-28T17:06:56 1_2_town current area isn't supported
2024-09-28T17:06:56 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:06:56 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:06:58 1_2_town current area isn't supported
2024-09-28T17:06:58 1_2_town current area isn't supported
2024-09-28T17:06:58 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:06:58 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:07:00 1_2_town current area isn't supported
2024-09-28T17:07:00 1_2_town current area isn't supported
2024-09-28T17:07:00 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:07:00 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:07:02 1_2_town current area isn't supported
2024-09-28T17:07:02 1_2_town current area isn't supported
2024-09-28T17:07:02 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:07:02 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:07:04 1_2_town current area isn't supported
2024-09-28T17:07:04 1_2_town current area isn't supported
2024-09-28T17:07:04 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:07:04 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:07:06 1_2_town current area isn't supported
2024-09-28T17:07:06 1_2_town current area isn't supported
2024-09-28T17:07:06 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:07:06 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:07:08 1_2_town current area isn't supported
2024-09-28T17:07:08 1_2_town current area isn't supported
2024-09-28T17:07:09 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:07:09 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:07:11 1_2_town current area isn't supported
2024-09-28T17:07:11 1_2_town current area isn't supported
2024-09-28T17:07:11 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:07:11 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:07:13 1_2_town current area isn't supported
2024-09-28T17:07:13 1_2_town current area isn't supported
2024-09-28T17:07:13 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:07:13 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:07:18 1_2_town current area isn't supported
2024-09-28T17:07:18 1_2_town current area isn't supported
2024-09-28T17:07:18 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:07:18 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:07:22 1_2_town current area isn't supported
2024-09-28T17:07:22 1_2_town current area isn't supported
2024-09-28T17:07:22 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:07:22 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:07:24 1_2_town current area isn't supported
2024-09-28T17:07:24 1_2_town current area isn't supported
2024-09-28T17:07:24 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:07:24 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:07:26 1_2_town current area isn't supported
2024-09-28T17:07:26 1_2_town current area isn't supported
2024-09-28T17:07:26 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:07:26 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:07:28 1_2_town current area isn't supported
2024-09-28T17:07:28 1_2_town current area isn't supported
2024-09-28T17:07:28 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:07:28 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:07:30 1_2_town current area isn't supported
2024-09-28T17:07:30 1_2_town current area isn't supported
2024-09-28T17:07:30 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:07:30 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:07:32 1_2_town current area isn't supported
2024-09-28T17:07:32 1_2_town current area isn't supported
2024-09-28T17:07:32 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:07:32 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:07:34 1_2_town current area isn't supported
2024-09-28T17:07:34 1_2_town current area isn't supported
2024-09-28T17:07:34 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:07:34 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:07:37 1_2_town current area isn't supported
2024-09-28T17:07:37 1_2_town current area isn't supported
2024-09-28T17:07:37 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:07:37 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:07:39 1_2_town current area isn't supported
2024-09-28T17:07:39 1_2_town current area isn't supported
2024-09-28T17:07:39 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:07:39 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:07:42 1_2_town current area isn't supported
2024-09-28T17:07:42 1_2_town current area isn't supported
2024-09-28T17:07:42 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:07:42 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:07:45 1_2_town current area isn't supported
2024-09-28T17:07:45 1_2_town current area isn't supported
2024-09-28T17:07:45 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:07:45 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:07:47 1_2_town current area isn't supported
2024-09-28T17:07:47 1_2_town current area isn't supported
2024-09-28T17:07:47 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:07:47 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:07:50 1_2_town current area isn't supported
2024-09-28T17:07:50 1_2_town current area isn't supported
2024-09-28T17:07:50 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:07:50 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:07:53 1_2_town current area isn't supported
2024-09-28T17:07:53 1_2_town current area isn't supported
2024-09-28T17:07:53 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:07:53 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:07:55 1_2_town current area isn't supported
2024-09-28T17:07:55 1_2_town current area isn't supported
2024-09-28T17:07:55 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:07:55 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:07:57 1_2_town current area isn't supported
2024-09-28T17:07:57 1_2_town current area isn't supported
2024-09-28T17:07:57 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:07:57 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:07:59 1_2_town current area isn't supported
2024-09-28T17:07:59 1_2_town current area isn't supported
2024-09-28T17:07:59 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:07:59 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:08:01 1_2_town current area isn't supported
2024-09-28T17:08:01 1_2_town current area isn't supported
2024-09-28T17:08:01 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:08:01 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:08:03 1_2_town current area isn't supported
2024-09-28T17:08:03 1_2_town current area isn't supported
2024-09-28T17:08:03 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:08:03 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:08:05 1_2_town current area isn't supported
2024-09-28T17:08:05 1_2_town current area isn't supported
2024-09-28T17:08:05 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:08:05 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:08:07 1_2_town current area isn't supported
2024-09-28T17:08:07 1_2_town current area isn't supported
2024-09-28T17:08:07 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:08:07 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:08:11 1_2_town current area isn't supported
2024-09-28T17:08:11 1_2_town current area isn't supported
2024-09-28T17:08:11 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:08:11 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:08:13 1_2_town current area isn't supported
2024-09-28T17:08:13 1_2_town current area isn't supported
2024-09-28T17:08:13 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:08:13 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:08:15 1_2_town current area isn't supported
2024-09-28T17:08:15 1_2_town current area isn't supported
2024-09-28T17:08:15 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:08:15 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:08:17 1_2_town current area isn't supported
2024-09-28T17:08:17 1_2_town current area isn't supported
2024-09-28T17:08:17 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:08:17 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:08:19 1_2_town current area isn't supported
2024-09-28T17:08:19 1_2_town current area isn't supported
2024-09-28T17:08:19 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:08:19 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:08:21 1_2_town current area isn't supported
2024-09-28T17:08:21 1_2_town current area isn't supported
2024-09-28T17:08:21 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:08:21 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:08:23 1_2_town current area isn't supported
2024-09-28T17:08:23 1_2_town current area isn't supported
2024-09-28T17:08:23 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:08:23 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:08:26 1_2_town current area isn't supported
2024-09-28T17:08:26 1_2_town current area isn't supported
2024-09-28T17:08:26 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:08:26 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:08:28 1_2_town current area isn't supported
2024-09-28T17:08:28 1_2_town current area isn't supported
2024-09-28T17:08:28 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:08:28 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:08:30 1_2_town current area isn't supported
2024-09-28T17:08:30 1_2_town current area isn't supported
2024-09-28T17:08:30 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:08:30 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:08:36 1_2_town current area isn't supported
2024-09-28T17:08:36 1_2_town current area isn't supported
2024-09-28T17:08:36 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:08:36 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:08:43 1_2_town current area isn't supported
2024-09-28T17:08:43 1_2_town current area isn't supported
2024-09-28T17:08:43 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:08:43 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:08:45 1_2_town current area isn't supported
2024-09-28T17:08:45 1_2_town current area isn't supported
2024-09-28T17:08:45 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:08:45 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:08:47 1_2_town current area isn't supported
2024-09-28T17:08:47 1_2_town current area isn't supported
2024-09-28T17:08:47 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:08:47 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:08:49 1_2_town current area isn't supported
2024-09-28T17:08:49 1_2_town current area isn't supported
2024-09-28T17:08:49 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:08:49 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:08:51 1_2_town current area isn't supported
2024-09-28T17:08:51 1_2_town current area isn't supported
2024-09-28T17:08:51 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:08:51 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:08:53 1_2_town current area isn't supported
2024-09-28T17:08:53 1_2_town current area isn't supported
2024-09-28T17:08:53 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:08:53 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:08:55 1_2_town current area isn't supported
2024-09-28T17:08:55 1_2_town current area isn't supported
2024-09-28T17:08:55 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:08:55 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:08:58 1_2_town current area isn't supported
2024-09-28T17:08:58 1_2_town current area isn't supported
2024-09-28T17:08:58 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:08:58 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:09:00 1_2_town current area isn't supported
2024-09-28T17:09:00 1_2_town current area isn't supported
2024-09-28T17:09:00 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:09:00 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:09:02 1_2_town current area isn't supported
2024-09-28T17:09:02 1_2_town current area isn't supported
2024-09-28T17:09:02 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:09:02 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:09:04 1_2_town current area isn't supported
2024-09-28T17:09:04 1_2_town current area isn't supported
2024-09-28T17:09:04 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:09:04 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:09:06 1_2_town current area isn't supported
2024-09-28T17:09:06 1_2_town current area isn't supported
2024-09-28T17:09:06 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:09:06 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:09:08 1_2_town current area isn't supported
2024-09-28T17:09:08 1_2_town current area isn't supported
2024-09-28T17:09:08 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:09:08 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:09:10 1_2_town current area isn't supported
2024-09-28T17:09:10 1_2_town current area isn't supported
2024-09-28T17:09:10 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:09:10 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:09:13 1_2_town current area isn't supported
2024-09-28T17:09:13 1_2_town current area isn't supported
2024-09-28T17:09:13 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:09:13 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:09:15 1_2_town current area isn't supported
2024-09-28T17:09:15 1_2_town current area isn't supported
2024-09-28T17:09:15 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:09:15 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:09:17 1_2_town current area isn't supported
2024-09-28T17:09:17 1_2_town current area isn't supported
2024-09-28T17:09:17 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:09:17 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:09:19 1_2_town current area isn't supported
2024-09-28T17:09:19 1_2_town current area isn't supported
2024-09-28T17:09:19 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:09:19 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:09:21 1_2_town current area isn't supported
2024-09-28T17:09:21 1_2_town current area isn't supported
2024-09-28T17:09:21 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:09:21 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:09:23 1_2_town current area isn't supported
2024-09-28T17:09:23 1_2_town current area isn't supported
2024-09-28T17:09:23 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:09:23 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:09:25 1_2_town current area isn't supported
2024-09-28T17:09:25 1_2_town current area isn't supported
2024-09-28T17:09:25 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:09:25 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:09:26 1_2_town current area isn't supported
2024-09-28T17:09:26 1_2_town current area isn't supported
2024-09-28T17:09:26 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:09:26 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:09:29 1_2_town current area isn't supported
2024-09-28T17:09:29 1_2_town current area isn't supported
2024-09-28T17:09:29 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:09:29 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:09:31 1_2_town current area isn't supported
2024-09-28T17:09:31 1_2_town current area isn't supported
2024-09-28T17:09:31 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:09:31 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:09:33 1_2_town current area isn't supported
2024-09-28T17:09:33 1_2_town current area isn't supported
2024-09-28T17:09:33 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:09:33 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:09:35 1_2_town current area isn't supported
2024-09-28T17:09:35 1_2_town current area isn't supported
2024-09-28T17:09:35 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:09:35 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:09:37 1_2_town current area isn't supported
2024-09-28T17:09:37 1_2_town current area isn't supported
2024-09-28T17:09:37 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:09:37 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:09:39 1_2_town current area isn't supported
2024-09-28T17:09:39 1_2_town current area isn't supported
2024-09-28T17:09:39 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:09:39 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:09:41 1_2_town current area isn't supported
2024-09-28T17:09:41 1_2_town current area isn't supported
2024-09-28T17:09:41 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:09:41 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:09:43 1_2_town current area isn't supported
2024-09-28T17:09:43 1_2_town current area isn't supported
2024-09-28T17:09:43 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:09:43 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:09:45 1_2_town current area isn't supported
2024-09-28T17:09:45 1_2_town current area isn't supported
2024-09-28T17:09:45 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:09:45 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:09:47 1_2_town current area isn't supported
2024-09-28T17:09:47 1_2_town current area isn't supported
2024-09-28T17:09:47 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:09:47 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:09:49 1_2_town current area isn't supported
2024-09-28T17:09:49 1_2_town current area isn't supported
2024-09-28T17:09:49 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:09:49 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:09:51 1_2_town current area isn't supported
2024-09-28T17:09:51 1_2_town current area isn't supported
2024-09-28T17:09:51 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:09:51 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:09:53 1_2_town current area isn't supported
2024-09-28T17:09:53 1_2_town current area isn't supported
2024-09-28T17:09:53 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:09:53 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:09:55 1_2_town current area isn't supported
2024-09-28T17:09:55 1_2_town current area isn't supported
2024-09-28T17:09:55 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:09:55 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:09:57 1_2_town current area isn't supported
2024-09-28T17:09:57 1_2_town current area isn't supported
2024-09-28T17:09:57 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:09:57 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:09:59 1_2_town current area isn't supported
2024-09-28T17:09:59 1_2_town current area isn't supported
2024-09-28T17:09:59 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:09:59 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:10:02 1_2_town current area isn't supported
2024-09-28T17:10:02 1_2_town current area isn't supported
2024-09-28T17:10:02 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:10:02 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:10:04 1_2_town current area isn't supported
2024-09-28T17:10:04 1_2_town current area isn't supported
2024-09-28T17:10:04 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:10:04 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:10:06 1_2_town current area isn't supported
2024-09-28T17:10:06 1_2_town current area isn't supported
2024-09-28T17:10:06 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:10:06 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:10:08 1_2_town current area isn't supported
2024-09-28T17:10:08 1_2_town current area isn't supported
2024-09-28T17:10:08 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:10:08 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:10:10 1_2_town current area isn't supported
2024-09-28T17:10:10 1_2_town current area isn't supported
2024-09-28T17:10:10 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:10:10 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:10:12 1_2_town current area isn't supported
2024-09-28T17:10:12 1_2_town current area isn't supported
2024-09-28T17:10:12 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:10:12 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:10:14 1_2_town current area isn't supported
2024-09-28T17:10:14 1_2_town current area isn't supported
2024-09-28T17:10:14 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:10:14 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:10:16 1_2_town current area isn't supported
2024-09-28T17:10:16 1_2_town current area isn't supported
2024-09-28T17:10:16 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:10:16 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:10:18 1_2_town current area isn't supported
2024-09-28T17:10:18 1_2_town current area isn't supported
2024-09-28T17:10:18 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:10:18 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:10:20 1_2_town current area isn't supported
2024-09-28T17:10:20 1_2_town current area isn't supported
2024-09-28T17:10:20 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:10:20 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:10:22 1_2_town current area isn't supported
2024-09-28T17:10:22 1_2_town current area isn't supported
2024-09-28T17:10:22 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:10:22 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:10:24 1_2_town current area isn't supported
2024-09-28T17:10:24 1_2_town current area isn't supported
2024-09-28T17:10:24 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:10:24 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:10:26 1_2_town current area isn't supported
2024-09-28T17:10:26 1_2_town current area isn't supported
2024-09-28T17:10:26 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:10:26 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:10:28 1_2_town current area isn't supported
2024-09-28T17:10:28 1_2_town current area isn't supported
2024-09-28T17:10:28 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:10:28 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:10:31 1_2_town current area isn't supported
2024-09-28T17:10:31 1_2_town current area isn't supported
2024-09-28T17:10:31 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:10:31 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:10:33 1_2_town current area isn't supported
2024-09-28T17:10:33 1_2_town current area isn't supported
2024-09-28T17:10:33 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:10:33 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:10:35 1_2_town current area isn't supported
2024-09-28T17:10:35 1_2_town current area isn't supported
2024-09-28T17:10:35 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:10:35 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:10:38 1_2_town current area isn't supported
2024-09-28T17:10:38 1_2_town current area isn't supported
2024-09-28T17:10:38 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:10:38 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:10:41 1_2_town current area isn't supported
2024-09-28T17:10:41 1_2_town current area isn't supported
2024-09-28T17:10:41 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:10:41 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:10:43 1_2_town current area isn't supported
2024-09-28T17:10:43 1_2_town current area isn't supported
2024-09-28T17:10:43 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:10:43 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:10:46 1_2_town current area isn't supported
2024-09-28T17:10:46 1_2_town current area isn't supported
2024-09-28T17:10:46 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:10:46 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:10:49 1_2_town current area isn't supported
2024-09-28T17:10:49 1_2_town current area isn't supported
2024-09-28T17:10:49 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:10:49 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:10:52 1_2_town current area isn't supported
2024-09-28T17:10:52 1_2_town current area isn't supported
2024-09-28T17:10:52 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:10:52 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:10:54 1_2_town current area isn't supported
2024-09-28T17:10:54 1_2_town current area isn't supported
2024-09-28T17:10:54 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:10:54 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:10:56 1_2_town current area isn't supported
2024-09-28T17:10:56 1_2_town current area isn't supported
2024-09-28T17:10:56 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:10:56 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:10:58 1_2_town current area isn't supported
2024-09-28T17:10:58 1_2_town current area isn't supported
2024-09-28T17:10:58 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:10:58 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:11:00 1_2_town current area isn't supported
2024-09-28T17:11:00 1_2_town current area isn't supported
2024-09-28T17:11:00 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:11:00 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:11:02 1_2_town current area isn't supported
2024-09-28T17:11:02 1_2_town current area isn't supported
2024-09-28T17:11:02 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:11:02 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:11:05 1_2_town current area isn't supported
2024-09-28T17:11:05 1_2_town current area isn't supported
2024-09-28T17:11:05 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:11:05 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:11:07 1_2_town current area isn't supported
2024-09-28T17:11:07 1_2_town current area isn't supported
2024-09-28T17:11:07 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:11:07 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:11:09 1_2_town current area isn't supported
2024-09-28T17:11:09 1_2_town current area isn't supported
2024-09-28T17:11:09 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:11:09 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:11:11 1_2_town current area isn't supported
2024-09-28T17:11:11 1_2_town current area isn't supported
2024-09-28T17:11:11 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:11:11 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:11:13 1_2_town current area isn't supported
2024-09-28T17:11:13 1_2_town current area isn't supported
2024-09-28T17:11:13 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:11:13 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:11:15 1_2_town current area isn't supported
2024-09-28T17:11:15 1_2_town current area isn't supported
2024-09-28T17:11:15 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:11:15 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:11:17 1_2_town current area isn't supported
2024-09-28T17:11:17 1_2_town current area isn't supported
2024-09-28T17:11:17 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:11:17 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:11:19 1_2_town current area isn't supported
2024-09-28T17:11:19 1_2_town current area isn't supported
2024-09-28T17:11:19 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:11:19 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:11:26 1_2_town current area isn't supported
2024-09-28T17:11:26 1_2_town current area isn't supported
2024-09-28T17:11:26 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:11:26 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:11:28 1_2_town current area isn't supported
2024-09-28T17:11:28 1_2_town current area isn't supported
2024-09-28T17:11:28 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:11:28 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:11:30 1_2_town current area isn't supported
2024-09-28T17:11:30 1_2_town current area isn't supported
2024-09-28T17:11:30 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:11:30 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:11:33 1_2_town current area isn't supported
2024-09-28T17:11:33 1_2_town current area isn't supported
2024-09-28T17:11:33 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:11:33 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:11:35 1_2_town current area isn't supported
2024-09-28T17:11:35 1_2_town current area isn't supported
2024-09-28T17:11:35 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:11:35 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:11:37 1_2_town current area isn't supported
2024-09-28T17:11:37 1_2_town current area isn't supported
2024-09-28T17:11:37 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:11:37 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:11:39 1_2_town current area isn't supported
2024-09-28T17:11:39 1_2_town current area isn't supported
2024-09-28T17:11:39 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:11:39 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:11:41 1_2_town current area isn't supported
2024-09-28T17:11:41 1_2_town current area isn't supported
2024-09-28T17:11:41 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:11:41 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:11:44 1_2_town current area isn't supported
2024-09-28T17:11:44 1_2_town current area isn't supported
2024-09-28T17:11:44 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:11:44 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:11:46 1_2_town current area isn't supported
2024-09-28T17:11:46 1_2_town current area isn't supported
2024-09-28T17:11:46 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:11:46 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:11:48 1_2_town current area isn't supported
2024-09-28T17:11:48 1_2_town current area isn't supported
2024-09-28T17:11:48 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:11:48 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:11:50 1_2_town current area isn't supported
2024-09-28T17:11:50 1_2_town current area isn't supported
2024-09-28T17:11:50 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:11:50 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:11:52 1_2_town current area isn't supported
2024-09-28T17:11:52 1_2_town current area isn't supported
2024-09-28T17:11:52 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:11:52 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:11:54 1_2_town current area isn't supported
2024-09-28T17:11:54 1_2_town current area isn't supported
2024-09-28T17:11:54 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:11:54 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:11:56 1_2_town current area isn't supported
2024-09-28T17:11:56 1_2_town current area isn't supported
2024-09-28T17:11:56 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:11:56 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:11:59 1_2_town current area isn't supported
2024-09-28T17:11:59 1_2_town current area isn't supported
2024-09-28T17:11:59 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:11:59 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:12:01 1_2_town current area isn't supported
2024-09-28T17:12:01 1_2_town current area isn't supported
2024-09-28T17:12:01 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:12:01 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:12:03 1_2_town current area isn't supported
2024-09-28T17:12:03 1_2_town current area isn't supported
2024-09-28T17:12:03 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:12:03 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:12:05 1_2_town current area isn't supported
2024-09-28T17:12:05 1_2_town current area isn't supported
2024-09-28T17:12:05 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:12:05 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:12:07 1_2_town current area isn't supported
2024-09-28T17:12:07 1_2_town current area isn't supported
2024-09-28T17:12:07 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:12:07 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:12:09 1_2_town current area isn't supported
2024-09-28T17:12:09 1_2_town current area isn't supported
2024-09-28T17:12:09 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:12:09 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:12:11 1_2_town current area isn't supported
2024-09-28T17:12:11 1_2_town current area isn't supported
2024-09-28T17:12:11 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:12:11 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:12:13 1_2_town current area isn't supported
2024-09-28T17:12:13 1_2_town current area isn't supported
2024-09-28T17:12:13 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:12:13 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:12:15 1_2_town current area isn't supported
2024-09-28T17:12:15 1_2_town current area isn't supported
2024-09-28T17:12:15 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:12:15 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:12:18 1_2_town current area isn't supported
2024-09-28T17:12:18 1_2_town current area isn't supported
2024-09-28T17:12:18 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:12:18 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:12:20 1_2_town current area isn't supported
2024-09-28T17:12:20 1_2_town current area isn't supported
2024-09-28T17:12:20 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:12:20 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:12:22 1_2_town current area isn't supported
2024-09-28T17:12:22 1_2_town current area isn't supported
2024-09-28T17:12:22 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:12:22 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:12:25 1_2_town current area isn't supported
2024-09-28T17:12:25 1_2_town current area isn't supported
2024-09-28T17:12:25 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:12:25 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:12:27 1_2_town current area isn't supported
2024-09-28T17:12:27 1_2_town current area isn't supported
2024-09-28T17:12:27 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:12:27 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:12:29 1_2_town current area isn't supported
2024-09-28T17:12:29 1_2_town current area isn't supported
2024-09-28T17:12:29 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:12:29 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:12:31 1_2_town current area isn't supported
2024-09-28T17:12:31 1_2_town current area isn't supported
2024-09-28T17:12:31 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:12:31 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:12:33 1_2_town current area isn't supported
2024-09-28T17:12:33 1_2_town current area isn't supported
2024-09-28T17:12:33 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:12:33 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:12:35 1_2_town current area isn't supported
2024-09-28T17:12:35 1_2_town current area isn't supported
2024-09-28T17:12:35 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:12:35 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:12:37 1_2_town current area isn't supported
2024-09-28T17:12:37 1_2_town current area isn't supported
2024-09-28T17:12:37 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:12:37 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:12:39 1_2_town current area isn't supported
2024-09-28T17:12:39 1_2_town current area isn't supported
2024-09-28T17:12:39 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:12:39 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:12:41 1_2_town current area isn't supported
2024-09-28T17:12:41 1_2_town current area isn't supported
2024-09-28T17:12:41 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:12:41 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:12:43 1_2_town current area isn't supported
2024-09-28T17:12:43 1_2_town current area isn't supported
2024-09-28T17:12:43 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:12:43 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:12:45 1_2_town current area isn't supported
2024-09-28T17:12:45 1_2_town current area isn't supported
2024-09-28T17:12:45 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:12:45 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:12:47 1_2_town current area isn't supported
2024-09-28T17:12:47 1_2_town current area isn't supported
2024-09-28T17:12:47 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:12:47 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:12:49 1_2_town current area isn't supported
2024-09-28T17:12:49 1_2_town current area isn't supported
2024-09-28T17:12:49 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:12:49 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:12:51 1_2_town current area isn't supported
2024-09-28T17:12:51 1_2_town current area isn't supported
2024-09-28T17:12:51 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:12:51 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:12:53 1_2_town current area isn't supported
2024-09-28T17:12:53 1_2_town current area isn't supported
2024-09-28T17:12:53 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:12:53 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:12:55 1_2_town current area isn't supported
2024-09-28T17:12:55 1_2_town current area isn't supported
2024-09-28T17:12:55 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:12:55 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:12:57 1_2_town current area isn't supported
2024-09-28T17:12:57 1_2_town current area isn't supported
2024-09-28T17:12:57 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:12:57 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:12:59 1_2_town current area isn't supported
2024-09-28T17:12:59 1_2_town current area isn't supported
2024-09-28T17:12:59 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:12:59 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:13:01 1_2_town current area isn't supported
2024-09-28T17:13:01 1_2_town current area isn't supported
2024-09-28T17:13:01 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:13:01 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:13:03 1_2_town current area isn't supported
2024-09-28T17:13:03 1_2_town current area isn't supported
2024-09-28T17:13:03 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:13:03 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:13:05 1_2_town current area isn't supported
2024-09-28T17:13:05 1_2_town current area isn't supported
2024-09-28T17:13:05 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:13:05 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:13:07 1_2_town current area isn't supported
2024-09-28T17:13:07 1_2_town current area isn't supported
2024-09-28T17:13:07 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:13:07 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:13:09 1_2_town current area isn't supported
2024-09-28T17:13:09 1_2_town current area isn't supported
2024-09-28T17:13:09 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:13:09 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:13:11 1_2_town current area isn't supported
2024-09-28T17:13:11 1_2_town current area isn't supported
2024-09-28T17:13:11 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:13:11 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:13:14 1_2_town current area isn't supported
2024-09-28T17:13:14 1_2_town current area isn't supported
2024-09-28T17:13:14 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:13:14 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:13:16 1_2_town current area isn't supported
2024-09-28T17:13:16 1_2_town current area isn't supported
2024-09-28T17:13:16 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:13:16 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:13:18 1_2_town current area isn't supported
2024-09-28T17:13:18 1_2_town current area isn't supported
2024-09-28T17:13:18 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:13:18 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:13:20 1_2_town current area isn't supported
2024-09-28T17:13:20 1_2_town current area isn't supported
2024-09-28T17:13:20 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:13:20 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:13:22 1_2_town current area isn't supported
2024-09-28T17:13:22 1_2_town current area isn't supported
2024-09-28T17:13:22 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:13:22 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:13:24 1_2_town current area isn't supported
2024-09-28T17:13:24 1_2_town current area isn't supported
2024-09-28T17:13:24 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:13:24 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:13:27 1_2_town current area isn't supported
2024-09-28T17:13:27 1_2_town current area isn't supported
2024-09-28T17:13:27 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:13:27 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:13:33 1_2_town current area isn't supported
2024-09-28T17:13:33 1_2_town current area isn't supported
2024-09-28T17:13:33 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:13:33 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:13:35 1_2_town current area isn't supported
2024-09-28T17:13:35 1_2_town current area isn't supported
2024-09-28T17:13:35 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:13:35 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:13:37 1_2_town current area isn't supported
2024-09-28T17:13:37 1_2_town current area isn't supported
2024-09-28T17:13:37 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:13:37 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:13:39 1_2_town current area isn't supported
2024-09-28T17:13:39 1_2_town current area isn't supported
2024-09-28T17:13:39 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:13:39 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:13:41 1_2_town current area isn't supported
2024-09-28T17:13:41 1_2_town current area isn't supported
2024-09-28T17:13:41 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:13:41 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:13:43 1_2_town current area isn't supported
2024-09-28T17:13:43 1_2_town current area isn't supported
2024-09-28T17:13:43 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:13:43 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:13:45 1_2_town current area isn't supported
2024-09-28T17:13:45 1_2_town current area isn't supported
2024-09-28T17:13:45 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:13:45 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:13:47 1_2_town current area isn't supported
2024-09-28T17:13:47 1_2_town current area isn't supported
2024-09-28T17:13:47 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:13:47 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:13:49 1_2_town current area isn't supported
2024-09-28T17:13:49 1_2_town current area isn't supported
2024-09-28T17:13:49 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:13:49 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:13:51 1_2_town current area isn't supported
2024-09-28T17:13:51 1_2_town current area isn't supported
2024-09-28T17:13:51 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:13:51 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:13:53 1_2_town current area isn't supported
2024-09-28T17:13:53 1_2_town current area isn't supported
2024-09-28T17:13:53 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:13:53 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:13:55 1_2_town current area isn't supported
2024-09-28T17:13:55 1_2_town current area isn't supported
2024-09-28T17:13:55 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:13:55 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:13:57 1_2_town current area isn't supported
2024-09-28T17:13:57 1_2_town current area isn't supported
2024-09-28T17:13:57 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:13:57 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:13:59 1_2_town current area isn't supported
2024-09-28T17:13:59 1_2_town current area isn't supported
2024-09-28T17:13:59 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:13:59 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:14:01 1_2_town current area isn't supported
2024-09-28T17:14:01 1_2_town current area isn't supported
2024-09-28T17:14:01 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:14:01 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:14:04 1_2_town current area isn't supported
2024-09-28T17:14:04 1_2_town current area isn't supported
2024-09-28T17:14:04 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:14:04 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:20:25 #resurrectAtCheckpoint call 1727515225.728664
2024-09-28T17:21:08 #resurrectAtCheckpoint call 1727515268.1066086
2024-09-28T17:21:24 #resurrectAtCheckpoint call 1727515284.569779
2024-09-28T17:23:08 #resurrectAtCheckpoint call 1727515388.9900298
2024-09-28T17:24:29 1_3_town current area isn't supported
2024-09-28T17:24:29 1_3_town current area isn't supported
2024-09-28T17:24:29 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:24:29 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:24:31 1_3_town current area isn't supported
2024-09-28T17:24:31 1_3_town current area isn't supported
2024-09-28T17:24:31 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:24:31 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:24:33 1_3_town current area isn't supported
2024-09-28T17:24:33 1_3_town current area isn't supported
2024-09-28T17:24:33 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:24:33 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:24:34 1_3_town current area isn't supported
2024-09-28T17:24:34 1_3_town current area isn't supported
2024-09-28T17:24:34 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:24:34 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:24:36 1_3_town current area isn't supported
2024-09-28T17:24:36 1_3_town current area isn't supported
2024-09-28T17:24:36 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:24:36 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:24:53 1_3_town current area isn't supported
2024-09-28T17:24:53 1_3_town current area isn't supported
2024-09-28T17:24:53 '  File "quest.py", line 4531, in <module>\n    current_quest_area = getQuestArea(poe_bot.game_data.area_raw_name)\n'
2024-09-28T17:24:53 '  File "quest.py", line 4521, in getQuestArea\n    raise Exception(f"{area_raw_name} current area isn\'t supported")\n'
2024-09-28T17:28:24 #resurrectAtCheckpoint call 1727515704.458484
